### ISSUE TITLE
hello! Great plugins set, but…

### ISSUE THREAD

**Issue by warb2n** [Ashung/Automate-Sketch#1]
Where **Remove All Unused Styles**? So sad…

**in Features** 
_Clear List_

- Clear Layer Name
- Clear Slices
- Clear Exportables
- Clear Guides
- Delete All Hidden Layers
- Delete All Hidden Layers in Artboard
- Delete All Empty Groups
- Delete All Empty Groups in Artboard
- Remove All Unused Styles

_Delete All Hidden Layers in Artboard_ 2 times but no _Remove All Unused Styles_
<img width="274" alt="screen shot 2016-10-15 at 08 34 45" src="https://cloud.githubusercontent.com/assets/6230166/19407716/9d759ae8-92b2-11e6-9574-4db59f4cdc65.png">

**UPD**  Aha got it _Delete All Hidden Layers in Artboard_ in end works like _Remove All Unused Styles_ just rename it =)

```
delete_all_hidden_layers_in_artboard: "Delete All Hidden Layers in Artboard"
delete_all_empty_groups: "Delete All Empty Groups"
delete_all_empty_groups_in_artboard: "Delete All Empty Groups in Artboard"
remove_all_unused_styles: "Delete All Hidden Layers in Artboard"
```

**Comment by warb2n** [comment]
And will be good if U can add _clear all layer styles_
because now not working plugins…

**Comment by Ashung** [comment]
Thank you.
