### ISSUE TITLE
Feature Request - swap multiple same value nested shared library overrides at once

### ISSUE THREAD

**Issue by creativechris08** [Ashung/Automate-Sketch#100]
would be amazing to have the option to swap multiple shared library nested overrides with the same value such as colour symbols or shared text symbols. i create different brands based on one source of truth (components) but then apply different colors and typography through nested shared library’s. it’s super time consuming to manullay change all my colour and text overides one by one. 

options could be
- change all shared library overrides with same value on current page to another or same shared library override value 
-change all shared library overrides with same value on current symbol to another or same shared library override value
-change all shared library overrides with same value on current artboard to another or same shared library override value.

i’ve been waiting months for a plugin that could do this but nothing seems to exists 😣 i feel your the sketch plugin god to make this happen 😎😎😎👍🏻

**Comment by Ashung** [comment]
For instances with same symbol master, you can select them by run "Automate" - "Symbol" - "Select All Instance of Symbol", then change the override in inspector panel.

I will add a override symbol replace feature like this.

![image](https://user-images.githubusercontent.com/932544/45544335-98c57180-b849-11e8-91a7-01471a8fac1a.png)

**Comment by Ashung** [comment]
"Symbol" - "Replace Override Symbol", for all instances in current page, you can select all layers then run "Replace Override Symbol".

**Comment by creativechris08** [comment]
<img width="2560" alt="screen shot 2018-09-20 at 13 26 46" src="https://user-images.githubusercontent.com/43187049/45815430-ed00a380-bcd8-11e8-9d3c-370b6117fcd6.png">
i would basically love to have the function to "find and replace" using only nested symbols. So in this case selecting all the yellow values (shared symbol) and replacing with "blue" value to create another brand quickly :) see attached screen shot.

**Comment by Ashung** [comment]
If you have selected layers, the Find popout menu will only list the nested symbols in selected layers, and have not selected layer will list all nested symbols in current document.
