### ISSUE TITLE
Text -> Capitalize not working

### ISSUE THREAD

**Issue by sogen** [Ashung/Automate-Sketch#103]
Only works when text is lowercase:

![screen shot 2018-09-29 at 6 18 08 pm](https://user-images.githubusercontent.com/2784323/46251604-4b81fc00-c414-11e8-8166-b0c88b31cd29.png)

Notice that any uppercase text won't get transformed correctly, as in examples 2 and 4.

**Comment by Ashung** [comment]
Fixed it.
