### ISSUE TITLE
Style > Rename Layer to Style Name not working on sketch 52

### ISSUE THREAD

**Issue by ascanio** [Ashung/Automate-Sketch#104]
I get this message with a layer selected with an style on and in the previous versions I did not get it
![image](https://user-images.githubusercontent.com/279210/46362706-51284d80-c671-11e8-9f4d-01068f6cdf30.png)

**Comment by Lustless** [comment]
Same thing! Please fix I really need it for my workflow

**Comment by Ashung** [comment]
Sorry I am on holiday, I will retrun home in 7th Oct. If the layer is a rectangle or oval, this will not working in Sketch 52, but working for flatted and composite shape.

**Comment by Lustless** [comment]
I am only looking to rename text layers but it doesn't seem to work

**Comment by Lustless** [comment]
Any chance this can be fixed before Oct 10th? I'm running a company design session and am introducing this plugin into the workflow. Would definitely love to showcase this amazing work you've done!

**Comment by Ashung** [comment]
@Lustless Fixed it, update to V52.1.20181008.

**Comment by ascanio** [comment]
@Ashung awesome!! thanks a lot! 👍
