### ISSUE TITLE
Paste and Replace Not Working in Sketch 52

### ISSUE THREAD

**Issue by mofo10169** [Ashung/Automate-Sketch#105]
When I use paste and replace, the original object does not get replaced, and the pasted object is to the left and 100px above the original object.

![artboard](https://user-images.githubusercontent.com/11966004/46439644-1b499e80-c72f-11e8-9d8a-be8413166399.jpg)

**Comment by richardsison** [comment]
Yeah just noticed this also. Seems to work for shapes and groups for me but not symbols though…?

**Comment by rodnem** [comment]
arrrggggg… same here

**Comment by Ashung** [comment]
Sorry I am on holiday, I will retrun home in 7th Oct.

**Comment by richardsison** [comment]
@Ashung All good mate. Enjoy!

**Comment by Ashung** [comment]
Fixed it, update to V52.1.20181008.
