### ISSUE TITLE
Feature Request - search & replace layer & text styles 

### ISSUE THREAD

**Issue by creativechris08** [Ashung/Automate-Sketch#106]
i was wondering if its possible using the new sketch 52.1 uppdate to add a new feature to your plugin; - an option to search and replace a certain layer style or text style within a page and / or a document.

for example,,,, 
i have 20 colour (layer styles) or 20 text styles for each of my brands (each brand separated on own page)  i then make a new duplicate page of the same brand, i now want to quickly search and replace  a certain layer style that would change throughout the whole page to another colour ( layer style) all in one go. this would make changing to a new brand very fast and easy,,,,,

awesome work ashung!! a true sketch plugin god!  👍🏻😎

**Comment by Ashung** [comment]
Update V52.1.20181008, you can use "Style" - "Select Layers by Layer/Text Style", then change the style in inspector panel.

I am planning to add a style override replace feature.

**Comment by creativechris08** [comment]
awesome 👍🏻😎 would it be possible to order the layer list a bit better? it’s hard to find which style as they are currently mixed in random order ( i have over 300text  styles) it’s a little hard to find exactly which size etc. good job dude

**Comment by creativechris08** [comment]
> Update V52.1.20181008 if you use Sketch 52.x, you can deselect layer, then run "Style" - "Select Layers by Layer/Text Style", and change the style in inspector panel.
> 
> I am planning to add a style override replace feature.

its a little messed up in 52.2 using abstract. It seems to be searching through old branches from abstract rather than my current branch masterfile and library. The option is also very confusing in terms of ordering as-well and it doesn't seem to find any style that im currently looking for? see screen shot....[](url)

**Comment by Ashung** [comment]
I think I can add  **Select Layers With Same Style**.

**Comment by creativechris08** [comment]
That would be awesome; Could you do this for both text and normal layer styles? and then to have a replace option? to page/document :)

**Comment by Ashung** [comment]
I and **Select Layers With Same Style** in  version 52.2.20181025. 
You can try this plugin, https://medium.com/makingtuenti/camilo-our-tool-and-technique-for-one-click-brand-change-in-sketch-52-2060ae4161ae?_branch_match_id=548738441202640578.

**Comment by creativechris08** [comment]
<img width="2868" alt="screenshot 2018-10-25 at 14 28 45" src="https://user-images.githubusercontent.com/43187049/47500163-55a3e880-d862-11e8-93c9-663978ec710b.png">
when having no artboards selected i cant seem to get this option working "select same layers by style" i am also getting an error where all my old branches are being showcased in the list?

**Comment by Ashung** [comment]
This is not for symbol override, you need to select 1 layer with shared style, then run this command.

**Comment by creativechris08** [comment]
i have uploaded some movies here that showcase the error

https://youtu.be/RblzOeUYIYQ
https://youtu.be/XfkAkdRT1xg

- Is it possible to make it possible through shared layer and text styles on symbols? :)

**Comment by creativechris08** [comment]
Put the HD option on for the youtube clips 👍

**Comment by creativechris08** [comment]
is it possible to do this with symbol overides? 👍

**Comment by creativechris08** [comment]
any luck with the the above improvement dude? :)

**Comment by creativechris08** [comment]
has sketch opened up any possibility in its API to have this function yet? search and replace text and layers styles through shared libraries? (  nested layers & text styles in symbols to a infinite depth )

**Comment by creativechris08** [comment]
Hi ashung, sketch has a new logic on its layered symbols and i wondered if the above (or attached image) could now work? "select all the same shared layer styles in the document and then to replace with a new shared layer style 

<img width="1526" alt="Screenshot 2019-07-15 at 13 34 26" src="https://user-images.githubusercontent.com/43187049/61213636-e4fd6e80-a705-11e9-878c-fc48c9fb742b.png">
