### ISSUE TITLE
问题：【基于类型选择选中对象内所有图层】部分功能异常 V52.1

### ISSUE THREAD

**Issue by thundercui** [Ashung/Automate-Sketch#108]
【基于类型选择选中对象内所有图层】部分功能异常：
1. 执行【选择形状图层】无效；
2. 执行【选择隐藏图层】和【选择透明图层】会将该图层和父级一起选中。

其他功能运行良好。

<img width="399" alt="2018-10-11 10 20 47" src="https://user-images.githubusercontent.com/26681956/46776819-e7c6cf80-cd3f-11e8-83c9-7491d4588cee.png">

**Comment by Ashung** [comment]
解决了，更新 V52.2.20181012。
