### ISSUE TITLE
Feature Request: Adjust Sizes

### ISSUE THREAD

**Issue by Shavcat** [Ashung/Automate-Sketch#113]
I think "Adjust Sizes" feature could be improved by changing small&large increasings from 1&10 pixels to 2&20 pixels. Thus there would be no pixel imperfect objects when we do small increasing.

I use Nudge Resize for a long time and I can tell that increasing/decreasing by 2&20 pixels are more convenient.

**Comment by Ashung** [comment]
The values can be change in “preferences” - “canvas”, default is 1 & 10.
