### ISSUE TITLE
Request to switch Text resize to auto

### ISSUE THREAD

**Issue by klin39** [Ashung/Automate-Sketch#115]
I have been having issue resizing a large about of text back into it's original size, and usually I use the auto/fixed toggle button under text section in the inspector. If it was possible to do it through Automate, I could map a shortcut to that, which could help me and others to speed up our workflow.

Thoughts?

**Comment by Ashung** [comment]
Update version 52.2.20181108, you can find it in menu "Automate" - "Text" - "Toggle Auto and Fixed".

**Comment by klin39** [comment]
Thank you so much!!
