### ISSUE TITLE
Feature Request: Character Count

### ISSUE THREAD

**Issue by StudioMastro** [Ashung/Automate-Sketch#117]
Would be awesome to have the chance to have a **character count** into the text panel. It's very helpful when designing for web and keep consistence with the **45to75 principle**. 

Right now I use this simple plugin just to do so: 
**https://github.com/andrewfiorillo/sketch-character-count**

I'm looking for a command that can **count the characters on a selected paragraphs** and/or if text is highlited into a paragraph to **count just the selected line**.

Thanks Ashung!

**Comment by Ashung** [comment]
Is this plugin not working?

**Comment by StudioMastro** [comment]
Dear Ashung,
I'll answer as Bertrand Russel will:

https://en.wikipedia.org/wiki/Barber_paradox

Or 

> If it's "no" then is "yes", if it's "yes" then is "no".

I'd like to have it in Automate 😄

**Comment by Ashung** [comment]
Update version  52.4.20181123.
