### ISSUE TITLE
Feature Request: Remove prototype hotspots & linkage

### ISSUE THREAD

**Issue by shannon-murdoch-webjet** [Ashung/Automate-Sketch#121]
I love this plugin and use the 'remove unused symbols' and 'remove hidden layers' functions regularly.

I'd love to see a simple addition to the plugin that allows removal of prototype-related functionality such as hotspots and linkage from elements to other artboards. At the moment to remove these is a very manual process (unless I'm mistaken).

Hope this can make it on the feature list.

**Comment by Ashung** [comment]
Update version 52.4.20181123, I add **Remove All Hotspot** and **Reset Flow** in prototyping menu.
