### ISSUE TITLE
Show library symbols with Same ID first in the list for Replace Symbol With Library Symbol

### ISSUE THREAD

**Issue by sreebhandaram** [Ashung/Automate-Sketch#122]
Hi guys,

Can we change the order of symbol list when you use the  "Replace Symbol With Library Symbol" feature to show ones with Same ID and Size first? This way we don't have to go hunting for symbols from a long list of similar sized symbols. 

--
Sree

**Comment by Ashung** [comment]
![image](https://user-images.githubusercontent.com/932544/49624435-607a9d00-fa0c-11e8-986b-413bce06cba2.png)
It is show ones with Same ID and Size first, then sort by name in current version.
