### ISSUE TITLE
Don't work "Sync Symbol Master From Sketch File base Symbol ID"

### ISSUE THREAD

**Issue by LenaAlyanova** [Ashung/Automate-Sketch#124]
I cann't sync my libraries after udate plugin 51.2.20180831
I get used to work with  Sync Symbol Master From Sketch File base Symbol ID ( http://prntscr.com/luj7yp) . But now nothing happens, when I selected  Library in the folder.
Can you help me please?

**Comment by richardsison** [comment]
@LenaAlyanova I've also raised this same issue [here](https://github.com/Ashung/Automate-Sketch/issues/120).

Haven't heard back from @Ashung yet though 😞. I've also found a similar issue occurs with Text Styles.

**Comment by LenaAlyanova** [comment]
@richardsison Yeah, I am still have this problem and  I am still waiting answer.
Maybe it will be help for you 
I use Automate plugin without updates
Sync Symbol Master From Sketch File base Symbol ID is worked in old plugin ( without updates)

**Comment by Ashung** [comment]
@LenaAlyanova can you tell me Sketch version and plugin version when plugin is not work?

**Comment by LenaAlyanova** [comment]
Sketch - 52.5
Plugin - 51.2.20180831

**Comment by Ashung** [comment]
Sorry, it is fixed now, I will release a version soon, or you can download a new version from [develop branch](https://github.com/Ashung/Automate-Sketch/tree/develop).

**Comment by LenaAlyanova** [comment]
Thank you! 
New version from develop branch is worked
