### ISSUE TITLE
Create Color/Typography Guide does not link to existing style

### ISSUE THREAD

**Issue by nathangross** [Ashung/Automate-Sketch#128]
Not sure if this is by design or not but when you use Create Typography Guide, none of the generated Type layers are linked to the existing style. I was really excited in using this feature to assess current styles, make necessary changes and update the styles. Is something like that possible using this Automate plugin?

**Comment by stegel** [comment]
this is an amazing plugin, and this action saved me so much time. BUT, I did have to go through assigning the text style to each element to make it perfect. This feature add would be great.
