### ISSUE TITLE
There are a lot of grammar and spelling errors in english

### ISSUE THREAD

**Issue by stegelsn** [Ashung/Automate-Sketch#132]
*First off, I love Automate!*

I am noticing a lot of slight grammar errors throughout the UI in English and would love to help clean them up. 

For example:
https://cl.ly/0b270318eae6 when runing "Replace Local Layer Styles with Library Styles"
_Reset all layer stytle_ with _Reset all layer styles_

How can I contribute to this?

**Comment by Ashung** [comment]
You can fork this repository and send pull request.

**Comment by seandellis** [comment]
This issue can now be closed since the work has been done.

https://github.com/Ashung/Automate-Sketch/commit/5a80639a13a42fa23d7dd43f22ec1144e7bee002
