### ISSUE TITLE
Imported Symbols Link Manage is crashing sketch 52.6

### ISSUE THREAD

**Issue by ahmedlmahmoud** [Ashung/Automate-Sketch#138]
The Imported Symbols Link Manage feature is crashing when I press cancel button 
And is it applicable to add filter for "symbol not found" to present it only ? Thank you.

**Comment by Ashung** [comment]
I add filter for "symbol not found" to new version. 

It is work for me, can you show me the error log.

**Comment by ahmedlmahmoud** [comment]
It's working now 🙏🏻

Thanks alot for adding this filter, What you think about adding a bulk option to unlink all missing symobls so I can replace them manually and maybe another option to recheck them in another library by name or id just like "symbol swapper" plugin

Thanks anyway, you saved us alot of hours 🙏🏻🙏🏻
