### ISSUE TITLE
“Tile Objects” functions UI panel focus is not on the text box

### ISSUE THREAD

**Issue by yanghaoleng** [Ashung/Automate-Sketch#141]
Hi！
关于Tile Objects那几项功能的面板，现在的默认的焦点在「取消」按钮上面，需要手动点击才能输入数值。能否把默认的焦点改回到文本输入框呢。好像更新53之后才出现的问题。

非常感谢！

**Comment by yanghaoleng** [comment]
发现一个新问题，例如执行 Tile Objects by Position Y 的时候，按下时 Esc 并不会取消，而是接生效。

**Comment by Ashung** [comment]
已修复。
