### ISSUE TITLE
Feature request: Rename symbols with overrides

### ISSUE THREAD

**Issue by fuzzze** [Ashung/Automate-Sketch#143]
Hi! First of all — tnx for a magic tool.
Look at this (probably tipical) case:
<img width="698" alt="screenshot 2019-02-13 at 18 28 36" src="https://user-images.githubusercontent.com/328808/52705398-be53d400-2fbd-11e9-9d8e-33b77d83094b.png">
Now users need to one-by-one rename symbol instances with names from override data.
<img width="719" alt="screenshot 2019-02-13 at 18 30 31" src="https://user-images.githubusercontent.com/328808/52705399-be53d400-2fbd-11e9-821c-352bfca216ac.png">
Maybe this work possible doing via script?

**Comment by Ashung** [comment]
I add "Symbol" - "Rename Instances Use Text Override", it's only work in Sketch 53+.

You need to select some symbol instances first, if the selected symbol instance have 1 text override, use this value for layer name, and if have more than 1 text override, you can choose which on for layer name. If you don't select any text override, use the first (top) text override for layer name.

**Comment by fuzzze** [comment]
Great work! Thank you!
