### ISSUE TITLE
Bug: "Replace Override Symbol" No Longer Working

### ISSUE THREAD

**Issue by blaskotron** [Ashung/Automate-Sketch#144]
Nothing happens when selecting this. No error, no window.

**Comment by blaskotron** [comment]
This is now missing from the menus completely. I used runner to search.

**Comment by blaskotron** [comment]
@Ashung This is now missing from the menus completely. I used runner to search.

**Comment by Ashung** [comment]
I removed it. Use Find and Replace Symbol instead.

**Comment by blaskotron** [comment]
I tried that, it's really confusing compared to Replace Overrides. 

The "Choose a Symbol" dropdown is not organized alphabetically. In everything but a small document it's very hard to find something. It needs to have a search. I think it needs to be filtered by what you choose to search in from the "Find Symbols in." Why would it show all symbols in document if I only care about the selection or artboard? 

It doesn't make sense that it asks you to choose a symbol twice. "Find a symbol in this document" and "Find Symbols In" dropdown. I don't know what to do with that when I first look at it. You might want this second one to be a radio toggle so it doesn't look so similar and change the name. This second dropdown needs to be next to the first search dropdown. 

Replace symbol from library or document doesn't make sense. Am I filtering what I'm searching for or what I'm replacing with?

Really struggling to get this to make sense. 

@Ashung
