### ISSUE TITLE
Adjust line to be on whole pixel

### ISSUE THREAD

**Issue by 12dylan34** [Ashung/Automate-Sketch#146]
Sometimes, Sketch draws lines on half pixels, which makes them fuzzy and not very crisp. This can be fixed by manually adding a ".5" to the end of the appropriate x/y dimension, but that's annoying. It would be nice if I could just do this in one click.
![screen shot 2019-02-14 at 8 52 36 am](https://user-images.githubusercontent.com/47637648/52798866-04e51500-3036-11e9-8e3d-016a38a72621.png)

**Comment by Ashung** [comment]
Sketch 53 have improved this.
