### ISSUE TITLE
"Show or Hide All Layout" returns "Please select an artboard or symbol master"

### ISSUE THREAD

**Issue by iconmaster** [Ashung/Automate-Sketch#147]
Sketch 53.1 (72631)

If an artboard is selected, or nothing is selected, "Show or Hide All Layout" performs as expected. If any layer is selected, the command returns an inline message of "Please select an artboard or symbol master." I suspect somehow another command is getting fired instead, but this is via direct selection from the menu.

**Comment by Ashung** [comment]
Grid and Layout visibility can be toggled for all selected Artboards in Sketch 53,  https://www.sketchapp.com/updates/#version-53), I will remove this feature.
