### ISSUE TITLE
Feature Request: 'Collapse All Groups' and 'Fit Canvas' across all pages in document

### ISSUE THREAD

**Issue by patttrick** [Ashung/Automate-Sketch#148]
Frequently, I'm using the 'collapse all groups' and 'fit canvas' commands to organize and tidy up my documents. I would be great to be able to apply these two commands to all pages in my document with a single command action.

**Comment by Ashung** [comment]
I add "Arrange" - "Collapse All Groups and Fit Canvas", but Sketch have an issue that can only run fit canvas at current page.
