### ISSUE TITLE
Feature request: Rename Text Inside of Text Layer to Style Name

### ISSUE THREAD

**Issue by AdamSabla** [Ashung/Automate-Sketch#149]
Would be really handy to have `Replace Text Inside of Text Layer with Style Name`.

**Comment by Ashung** [comment]
I add "Text" - "Change Texts", it can change text value with style name, it works like RenameIt but change text value.

![image](https://user-images.githubusercontent.com/932544/53802248-58cf8380-3f7c-11e9-8094-dae0c9d14b1c.png)
