### ISSUE TITLE
hide/show all grid/layout

### ISSUE THREAD

**Issue by BrettArchibald** [Ashung/Automate-Sketch#151]
Why did you remove "hide/show all grid/layout" in the latest release? :-(
I really need this feature...

**Comment by Ashung** [comment]
#147 Sketch 53 support show/hide all grid/layout.

**Comment by BrettArchibald** [comment]
But it doesn't work properly in the 53 release!
In the latest version, when I de-select an object and click on an empty / blank section of the Artboard, then hitting Ctrl-L does nothing. The option to View/Hide Layout is disabled unless either an object ON the Artboard is selected (or if I scroll up to the top of the Artboard or the Layer List and select the Artboard's name).

**Comment by Ashung** [comment]
cmd-shift-A then control-G/L

**Comment by BrettArchibald** [comment]
That's TWO keyboard shortcuts.

**Comment by Ashung** [comment]
I add a new Hide or Show All Grid / Layout.

**Comment by BrettArchibald** [comment]
A thousand thank-you's!!! :-) 👍

**Comment by BrettArchibald** [comment]
![image](https://user-images.githubusercontent.com/48060014/53805308-b5fa1380-3f41-11e9-993c-631682d2ac54.png)
