### ISSUE TITLE
问题：【基于名称选择选中对象内所有图层】表现异常，V52.6

### ISSUE THREAD

**Issue by thundercui** [Ashung/Automate-Sketch#153]
在Sketch v52.6中使用 53.2.20190304 的【基于名称选择选中对象内所有图层】功能时，执行的是选中子图层，而不是输入图层名称对话框。

我为了继续使用[Paddy](https://github.com/DWilliames/paddy-sketch-plugin?ref=jydesign)插件，决定停留在 v52.6 不再更新新版的 Sketch，请问 Automate-Sketch 之后的升级是否不再考虑兼容 Sketch v53 之前的版本了呢？如果是的话，我就停留在 Automate-Sketch 的 53.0.20190213 版，不再更新和上报兼容方面的问题。

当前版本的功能对我也够用了🙏

**Comment by Ashung** [comment]
不好意西，这个是翻译的文字位置错了。“基于名称选择选中对象内所有图层” 和 “选择选中对象内所有子图层” 反了。下次更新修复。

可以继续更新插件，旧的功能除非因为 Sketch 本身改动特别大才会考虑不向下兼容，新增的功能一般都不考虑兼容旧版，有些情况也是因为新增功能使用了新版的功能。

插件版本号前 2 段数字表示在对应的 Sketch 版本上开发和测试的，如果旧版本 Sketch 升级插件导致旧的功能不兼容，可以从[这里](http://ashung.github.io/Automate-Sketch/)按时间顺序找到更新前的上一个版本。等到你的 Sketch 升级之后再更新对应版本的插件。

**Comment by thundercui** [comment]
我明白了，十分感谢你 🙏
