### ISSUE TITLE
Rename layer name to style name removed?

### ISSUE THREAD

**Issue by seehadley** [Ashung/Automate-Sketch#154]
I noticed that renaming the layer name to the style name was removed in the latest update. Is there any chance that this will be reintroduced? It's extremely useful to my workflow.

Thanks for everything!

**Comment by Ashung** [comment]
In new version you can use "Layer" - "Rename Layers".

![image](https://user-images.githubusercontent.com/932544/53928305-94756500-40c4-11e9-9f42-d5caf55038b7.png)

**Comment by seehadley** [comment]
Got it, thanks @Ashung for the response.
