### ISSUE TITLE
"Raname Layers" misspelling of rename

### ISSUE THREAD

**Issue by Q-Hendrik** [Ashung/Automate-Sketch#155]
Automate -> Layer -> Raname Layers

Misspelling of the word "Rename".

**Comment by erausch** [comment]
Also found in: 

https://github.com/Ashung/Automate-Sketch/blob/8b81622ec8ec9404651a04722b5471d472c1acfc/automate-sketch.sketchplugin/Contents/Resources/manifest_en.json#L1211

**Comment by Ashung** [comment]
Fixed, update 53.2.20190315
