### ISSUE TITLE
Selecting individual or multiple text styles to change to a library style

### ISSUE THREAD

**Issue by darrenhead** [Ashung/Automate-Sketch#156]
Hey, awesome plugin! Love it.

Would it possible to add more functionality to **"Change local text style to library text style"**?

For example, I have many text styles in my library (1000+), and when I try to use the automate task above it crashes sketch. To break this up into smaller chunks can you add the ability to only commit this task on single or multiple selected styles?

This would also be helpful for Layer styles too.

Many thanks!

**Comment by Ashung** [comment]
You can use "Style" - "Select Layers by Text/Layer style" or "Select Layers with same shared style", to select layers, then replace style in inspector panel.
