### ISSUE TITLE
Feature Request: Flatten Group

### ISSUE THREAD

**Issue by blaskotron** [Ashung/Automate-Sketch#159]
When you apply a transform such as rotation to a group, the amount is not permanent and you can still see the amount in the rotation field. If you don't flatten it, it can cause other strange behaviors in future transforms. 

To flatten a group you have to ungroup everything, which moves the transform to each child in the group. Then you have to flatten each shape (Layer > Combine > Flatten) and then re group it. 

I think this would be a useful and time saving feature to just immediately flatten all selected objects or group. Thank you.

**Comment by Ashung** [comment]
You can't use flatten in a combined shape layer, you need a feature like [Reset Bounding Box](http://www.adobepress.com/articles/article.asp?p=1928525&seqNum=5) in Adobe Illustrator.

**Comment by blaskotron** [comment]
Yeah and I'd want to reset bounds on not just shapes, but symbols and groups too.
