### ISSUE TITLE
"Disable or enable all overrides" not always working

### ISSUE THREAD

**Issue by Arroyodorado** [Ashung/Automate-Sketch#160]
I really missed this feature being native to Sketch, so I'm glad you did it! 8-)

But unfortunately it doesn't work reliably, when you put symbols inside symbols and these inside symbols and so on. Sometimes I turn a whole artboard into a symbol to use it in various places. And exactly in this case I'd like to turn off all those many many overrides. But with a level of 4 nestings, I can't get the command to work. Level 3 works sometimes or almost always. 2 and 1 are super fine. And this level 4 happens quite quickly – you put an icon-symbol inside a button-symbol, that button inside some bigger component-symbol and turn the artboard around it ot a symbol and there you have it.

I also found out, that it has something to do with the number of symbols used on each level. Nested single symbols do work at level 4, complex arrangements don't. 

I already had a look at the code but it's a bit too complex for me to fully understand. But somehow the manageOverrides array ends up being empty. It may have to do something with that splice-loop… but I don't know exactly. I prepared a Sketch file for you to reproduce the bug.

And may I suggest to put the "disable" and the "enable" function in two different menu commands? Just for clarity…

Thank you for all your efforts and your work for the plugin. It's my most used plugin in Sketch as it fills so many holes that the developers leave.

Cheers 8-)

[reproduceTheBug.zip](https://github.com/Ashung/Automate-Sketch/files/2990243/reproduceTheBug.zip)

**Comment by Ashung** [comment]
This bug is fixed, I'will release soon.

**Comment by Arroyodorado** [comment]
Great! Thank you very much! 8-)
