### ISSUE TITLE
Feature Request: Make Exportable SVG. PNG. JPG

### ISSUE THREAD

**Issue by highvoltaged** [Ashung/Automate-Sketch#163]
Would love to have a keyboard shortcut to set a layer to exportable SVG, PNG, JPG

I don't really care for size and suffix settings, just the basic function when you click on the button.

Thanks for you wonderful work, saves my ass hundreds of times a day.

**Comment by sogen** [comment]
Fast slice has a shortcut, or you can add one in your System settings.

**Comment by Ashung** [comment]
I add Quick Export features, you can direct export selected layers use any export presets in "Preferences" - "Presets" panel.

![image](https://user-images.githubusercontent.com/932544/55324991-47fc2a00-54b6-11e9-8974-d8d34c748a0a.png)

**Comment by highvoltaged** [comment]
Yeah, but i'm not talking about slices, cause i never use those. 
I'm talking about the "Layer/Make Exportable" function. 
http://prntscr.com/n5us4t
Only problem with that, is that it defaults to PNG. 

This shortcut would set it to SVG, or JPG respectively.

Like 'Make Exportable SVG' and 'Make Exportable JPG''

**Comment by Ashung** [comment]
Why add "Make Exportable" for layers?

**Comment by Ashung** [comment]
"Make Exportable" use the default preset in "Presets" panel.

**Comment by highvoltaged** [comment]
> "Make Exportable" use the default preset in "Presets" panel.

Ok thanks i did not know that, but i would like to have different presets, and if the Quick Export feature would work without slices, than it would be great
