### ISSUE TITLE
Ordering layers should order selection too.

### ISSUE THREAD

**Issue by ozgurgunes** [Ashung/Automate-Sketch#166]
Hi, first of all; thanks for this awesome plugin, I can't live without this :)

I have a little request if possible:

`Arrange > Order Layers By...` & `Arrange > Reverse Layer Order` are the commands I use a lot. But these commands are ordering layers only, order of selection stays intact. So; if you run any other order related command (like Rename It with sequence options) following these, new command is being applied with old ordering. To avoid this situation; you have to deselect all layers and select again before running other commands.

It will be great if these commands update the selection order as well as the layer order.

Thanks again.

**Comment by Ashung** [comment]
Fix it.
