### ISSUE TITLE
Feature request: Insert SVG Code in the middle of the screen

### ISSUE THREAD

**Issue by sogen** [Ashung/Automate-Sketch#168]
Hi, would appreciate for Insert SVG Code to be able to insert it in the middle of the screen.
It currently inserts them at 0,0, but if I'm in coordinates 2000,2000, I have to scroll back to find where I was in the document.
Thanks!

**Comment by Ashung** [comment]
When you select a layer the SVG will move to the same place of the layer, if you select a group or artboard the SVG will move into the group.

I'll make the SVG in the center of canvas if select nothing.

**Comment by sogen** [comment]
> When you select a layer the SVG will move to the same place of the layer, if you select a group or artboard the SVG will move into the group.
> 
just noticed the new feature, very helpful :) 
> I'll make the SVG in the center of canvas if select nothing.

great, thanks!
