### ISSUE TITLE
Feature request: symbol/set to none in all instance

### ISSUE THREAD

**Issue by Raghav789** [Ashung/Automate-Sketch#174]
Sometimes when I update a symbol by adding an additional symbol within it, I would like to set it to none in all previously place symbol in instances.
For example: I created an app bar symbol with two icons, and used it in several artboards, after a while I run into a scenario where I need three icons in the app bar symbol so after adding an extra symbol, I've to manually go back to all the previously placed instances of the symbol and set the new symbol to one.
Thank you

**Comment by Ashung** [comment]
Select 1 symbol instance, run "Symbol" - "Select All Instances of Symbol", then change the override to none in inspector.
