### ISSUE TITLE
Order of items when using Data > Text From File

### ISSUE THREAD

**Issue by panoptican** [Ashung/Automate-Sketch#175]
When using the `Text From File` option, the order of item replacement is very loosely randomized. Is the intent for it to be in the same order as text file? Given that the other option is `Random Text From File`, I assumed that `Text From File` would maintain the same order.

![CleanShot 2019-06-12 at 08 04 42](https://user-images.githubusercontent.com/1971835/59353611-fdceca80-8ce8-11e9-9f6a-d9221f03e94e.gif)

**Comment by Ashung** [comment]
![image](https://user-images.githubusercontent.com/932544/59398259-1959d400-8dc2-11e9-81b1-f105ae81a248.png)

**Comment by panoptican** [comment]
Ah! Got it. Thanks for the explanation.
