### ISSUE TITLE
Replace all selected layers with a Symbol

### ISSUE THREAD

**Issue by collarbone** [Ashung/Automate-Sketch#176]
It'd be great to be able to select all layers with the same name (or however they are selected - not just by name), then to replace those layers with a symbol. So if I have the same button in 30 places, I can create a symbol, select all layers with the same name, then replace with the symbol. This way I don't need to go replace all instances of the same object with a symbol manually. I'd be happy to donate some money if you can get this feature into the `Symbols` area of the plugin. Would save a lot of time.

**Comment by Ashung** [comment]
Use "Automate" - "Layer" - "Paste and Replace".

**Comment by collarbone** [comment]
Awesome. Thank you so much. Amazing work.
