### ISSUE TITLE
Regression: Rename All Instances

### ISSUE THREAD

**Issue by tbnv** [Ashung/Automate-Sketch#18]
Hello,

Why did you remove "Rename All Instances"? I see there is "Rename Instances" but it doesn't work. I use it many many times each day. :)

**Comment by Ashung** [comment]
I never remove "Rename All Instances",  I change the name. "Automate" - "Symbol" - "Rename Instances", while you select artboard/group it will rename all instances in selected artboard/group, and select instance it will rename the selected instance, and if select nothing it will rename all instances in current page.

**Comment by tbnv** [comment]
Sorry @Ashung, I don't understand what you explain… 🙁

On my side, there is a big difference between the action named "Rename All Instances" in the old version of the plugin and the one called "Rename Instances" in the new version.

- Old: https://shrrr.it/Pq6oUEFH8kiLG3nRc5zz.mp4
- New: https://shrrr.it/JC5DtHGMyi9tKunfUNn2.mp4

As you can see, with the new version of the plugin, instances of the symbol are *not* renamed in other pages. If you just changed the name of the action, then there is a bug somewhere.

Do you see what I mean?

**Comment by Ashung** [comment]
Sorry, there is no bug. I rewrite the code, if you want to rename all instances in document, don't select any layer.

I think I must add a dialog like this.

- [ ] Rename all instances.
- [ ] Rename instances in selected Artboard or Group.
- [ ] Rename instances in current Page.

**Comment by tbnv** [comment]
Yeah why not. I’d also add an option to offer the same behavior as before, allowing to rename all instances of the selected symbol in all artboards from all pages. Don’t you think all this was easier before? :-) Anyway, in order to keep this feature that I really need, I’ll revert back to the older version of the plugin.

**Comment by tbnv** [comment]
Thanks a lot @Ashung, the new update works like a charm.
