### ISSUE TITLE
Toggle On/Off "Adjust Content on Resize"

### ISSUE THREAD

**Issue by TylerFAnderson** [Ashung/Automate-Sketch#181]
Hello Sketch Master Ashung,

I was wondering if you could implement this small feature request. My team and I often turn off an artboard or symbol artboard's ability to "Adjust Content on Resize." Often times, we find this toggle already enabled and it is very annoying, especially when we use your Automate feature: "Automate>Artboard>Resize to Fit Height" and content gets smushed around (usually when inner elements aren't pinned correctly). 

My team and I would love the ability to turn off (i.e. toggle off) "Adjust Content on Resize" for every artboard in the .Sketch document. The attached photo shows it turned on, but we would love to be able to turn all of them off with one simple action. 

Thank you!

Tyler & Team

![image](https://user-images.githubusercontent.com/10507569/59952112-1194d200-9449-11e9-9330-e4d827e05e91.png)

**Comment by TylerFAnderson** [comment]
To expand on this slightly, if it is equally easy for you on the development end, our team would be extremely happy with the option to just completely turn off "Adjust Content on Resize" permanently. For all current and future new Sketch documents. Not sure how feasible that is for you, but that is the ideal functionality we would be looking for. Thanks!

**Comment by Ashung** [comment]
I added "Artboard" - "Toggle Adjust Content on Resize", update version 55.2.20190625.

You can use cmd - shift - a to select all artboard and symbol master in current page, then run "Artboard" - "Toggle Adjust Content on Resize".
