### ISSUE TITLE
Feature request: Hide menu items

### ISSUE THREAD

**Issue by schoi312** [Ashung/Automate-Sketch#182]
Feature request: Ability to hide menu items. There are many features in Automate, but not all are useful to every user, which creates clutter for them. The ability to hide menu items would cut down on the visual clutter and make it easier for users to find what they're looking for.

Attached is a screenshot of how Adobe Photoshop handles it. Something like that would be great.
![Screen Shot 2019-06-25 at 11 31 13 AM](https://user-images.githubusercontent.com/52213293/60116286-5bc5ce00-973d-11e9-999d-d28a9e0db587.png)

**Comment by Ashung** [comment]
You can use [Sketch Runner](https://sketchrunner.com/l)
