### ISSUE TITLE
图层按画板分别编组

### ISSUE THREAD

**Issue by Banlanhei** [Ashung/Automate-Sketch#191]
需求描述：选中多个画板中的多个图层执行编组命令，每一个画板内的选中图层分别生成一个组。希望提供一下这个功能啊，感谢~

**Comment by uwings** [comment]
顶一下，今天也有这个需求，没办法只能手动。   在多个画板或多个 symbols 每个组分别成组

**Comment by Ashung** [comment]
这个操作都用来做什么？
