### ISSUE TITLE
Feature Request: Assign (custom) keyboard shortcuts to Automate Sketch features

### ISSUE THREAD

**Issue by asaf-design** [Ashung/Automate-Sketch#194]
Being able to assign keyboard shortcuts (KS) to Automate will help to improve the workflow. Obviously, not all features could have KS (collides with other plugins, etc.) but it would be great to let users assign a custom KS for features that they use more often.

**For example:**
If I am zoomed in an artboard and want to select the artboard itself my options are:
- Go to the layer list and select it there
- Zoom out until I can select the artboard
- Use automate and go through several menus until I reach "Select Parent Artboard" (a Super useful feature by itself!).

As a user, I would love to be able to assign a keyboard shortcut to this feature so I can select the parent artboard quickly.

The above is one example but there are many Automate Sketch features that I have embedded in my workflow and use frequently and I would love to assign KS to so I can work even faster.

Thank you!
Asaf

**Comment by Ashung** [comment]
You can use Sketch Runner, or use “System Preferences” - “Keyboard” preference panel.
