### ISSUE TITLE
Bug: "Replace Symbol with Library Symbol" only replaces first one

### ISSUE THREAD

**Issue by Arkkimaagi** [Ashung/Automate-Sketch#197]
I am unable to replace overrides from multiple symbols at once. I have tried by selecting all my symbols and none. It just seems to replace in the first symbol and not in the others.

It would be ok to run the plugin multiple times, but I have to select from two dropdowns each time I run it.

Am I doing something wrong?

**Comment by Ashung** [comment]
**Replace Symbol with Library Symbol** replace local symbol to library symbol.  It just replace 1 symbol, but you can choose any symbol even with different name, size in a library. 

**Change Local Symbols to Library Symbol** replace multiple local symbols to library symbols with same name or id.

**Comment by Arkkimaagi** [comment]
Ok, i just have about a hundred icon symbols each inside their own artboard with a correct filename. Creating them again by duplicating and replacing symbol is a big task.

For now I will just have to click click click...

I will try to take a look at the plugin and see if I can make a pull request at some point.
