### ISSUE TITLE
求功能！

### ISSUE THREAD

**Issue by YolandaKim** [Ashung/Automate-Sketch#2]
https://github.com/lmwebdesign/Sketch3-ColorSwitch
请问，是否可以提供这样的一个功能。关于快速填充颜色的设置（定义颜色色值+定义快捷键）在工作中非常高频实用，可惜它目前新版本里似乎失效了。

**Comment by Ashung** [comment]
这个需要自己改颜色的代码太麻烦了。我试下能不能给全局色板加快捷键。

**Comment by Ashung** [comment]
ctrl/alt/cmd/shift 加数字的快捷键都被占用了.

**Comment by Ashung** [comment]
在 Styles 类下增加
- Fill Color from Global Colors 从全局色版快速填充
- Fill Color from Document Colors 从文档色版快速填充

或者使用 https://github.com/Ashung/QuickColor （原版https://github.com/colesperks/QuickColor）， 我修复了 41 支持和全局色彩支持。
