### ISSUE TITLE
Figma plugin?

### ISSUE THREAD

**Issue by n-w-o** [Ashung/Automate-Sketch#201]
hi, any plans to support Figma?

**Comment by Banlanhei** [comment]
希望提供一下Figma版插件哈

**Comment by Banlanhei** [comment]
希望提供一下Figma版插件，下面这些功能比较有用：

**Comment by Banlanhei** [comment]
希望提供一下Figma版插件，下面这些功能比较有用：
1. 图层快速排序
2. 批量创建样式
3. 批量创建组件
