### ISSUE TITLE
Request for "Increase/Decrease font weight" change default bold weight

### ISSUE THREAD

**Issue by klin39** [Ashung/Automate-Sketch#203]
I often find myself using semibold instead of bold, and would like a simpler way to get that with just keyboard. If there was a way to increase/decrease font weight under the text section, that would help a lot. The best solution would be to be able to remap cmd+b to toggle to a different font weight, but I'm not sure how possible that is.

Thanks!
Kevin L

**Comment by Ashung** [comment]
I can't increase/decrease font weight, because ExtraLight and Light have same font weight in Sketch plugin, but I can change the font to another weights in font weight select menu.

**Comment by klin39** [comment]
Being able to toggle through the next/prev font weights would still be awesome and greatly appreciated!
