### ISSUE TITLE
Replace imported symbols from a specific library

### ISSUE THREAD

**Issue by YoannSwap** [Ashung/Automate-Sketch#211]
If you want to replace imported symbols from a specific library to another one, it replaces all the imported symbols from all your library instead of the one you selected.

**Comment by Ashung** [comment]
If you want to only repleace the symbols you selected, use the "Replace With" in right click menu.

**Comment by YoannSwap** [comment]
Hey, thanks for your answer but I don't want to replace symbols that i've selected, I would like to replace all the imported symbols of my document from a specific library to another library.
As i said above, when i use "Automate / Library / Replace Library" and select one library for "Libraries of Imported Objects", it is not considering my choice because it replaces all the imported components of my document from all the libraries.

**Comment by Ashung** [comment]
Fixed, update new version.
