### ISSUE TITLE
Bug: "Replace Library" is not working in Sketch 58

### ISSUE THREAD

**Issue by korajasekar** [Ashung/Automate-Sketch#213]
This option is not working in latest version of Sketch. 
It shows: Replace 0 symbol from "Library A" to "Library B".

**Comment by FedorBoretsky** [comment]
me too

**Comment by rajasekar-novopay** [comment]
I'm using this in the meantime: https://github.com/sketch-hq/library-replacer-sketchplugin

**Comment by FedorBoretsky** [comment]
Thank you @rajasekar-novopay
