### ISSUE TITLE
"Remove Redundant Groups" doesn't seem to be working

### ISSUE THREAD

**Issue by mrrocks** [Ashung/Automate-Sketch#22]

**Comment by mrrocks** [comment]
This seems to be broken again in the latest version.

**Comment by Ashung** [comment]
@mrrocks it works, you need to select group, artboard or nothing.

**Comment by mrrocks** [comment]
I've tried every way and nothing…

**Comment by Ashung** [comment]
I use Sketch 45.2, Automate 2.0.20170720, and it works, try to update Sketch and plugin.

**Comment by mrrocks** [comment]
It works again on the latest plugin version 👍
