### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jazzybeat** [Ashung/Automate-Sketch#221]
It would be great if there was an option to arrange selected layers in the Side Layer Window to match the visual arrangement that is in the artboard.

![Screenshot 2019-11-05 at 19 51 28](https://user-images.githubusercontent.com/815706/68236853-3f4c7300-0006-11ea-8117-ad609b2dd973.png)

**Comment by Ashung** [comment]
Use "Arrange" - "Order Layers By ..." -> "Position Y (Top-Bottom)" or "Position Y (Bottom-Top)" .
