### ISSUE TITLE
Syncing one library symbol at a time

### ISSUE THREAD

**Issue by rekker** [Ashung/Automate-Sketch#222]
Hi,

We've built a fairly large and complex design system using Sketch and Abstract and every now and then a bug in the imported library symbols appear. The library wont show the imported symbol accurately (while the link is intact). Usually pressing the "File > Sync Library Components ..." button will fix all this and everything looks as it is supposed to do afterwards. However, this syncing is now taking so long that it uses up all memory disk space (up to 200gb) crashing my computer, therefore unable to fix this issue. When I wrote to sketch about this they advised to break up the files, which we have done to a certain extend but are unable to break it up further. It still occurs and it is so bad that it is blocking our work now. A possible solution could be to execute this syncing per component (and nested components) so that I could do this for one component at at time so that it doesn't crash my computer. I've tried your "Update selected library symbol" but that actually made a bug appear on that symbol. Do you have a solution for this?

**Comment by Ashung** [comment]
What bug?

**Comment by rekker** [comment]
It broke the link between the instance and the symbol in the library. I know this because a normally hidden layer in the symbol instance now appears. Normally running "File > Sync Library Components..." would fix this and hide the layer again, which is exactly what I can't do due to capacity issues of my computer.. it ramps up to 200+gb of disk space.
