### ISSUE TITLE
Add guides based on selected layer

### ISSUE THREAD

**Issue by ziyafenn** [Ashung/Automate-Sketch#223]
Right now, when selecting a layer, Ruler highlights that selection. It would be amazing to be able to automatically create guides based on the layer selection (for selected layer)!

There is a plugin for it which is not supported anymore: https://github.com/pratikjshah/Sketch-Guides

**Comment by Ashung** [comment]
I add "New Guides", "New Guide Layout" and "New Guide from Layer" like photoshop
