### ISSUE TITLE
Style > Create Typography Guide doesn't recognise styles in a Shared Library ?

### ISSUE THREAD

**Issue by steveharman** [Ashung/Automate-Sketch#225]
Hi,

I have a Sketch file whil feeds from a Shared Library, where all our layer & text styles live.

When I use Automate > Style > Create Typography Guid,e the output only seems to contain styles from my local Document?  It doesn't contain the styles _used_ by my document but contained in the Shared Library.

Is that expected behaviour?  With the popularity of "Design Systems",  It would be far more useeful to  reflect the text styles used in my work no matter where their styles actually are -  in a Shared Library for example.

Related point: I just noticed that, similar to typography, if I use Create **Color** Guide the same thing seems to be true?   All my colours are in the Shared Library not the local document, so Automate Sketch finds no colours or gradients despite there being around 10 in use.

Thanks,

Steve

**Comment by Ashung** [comment]
I'll add this feature in next version.
