### ISSUE TITLE
missing plugin some menu items in Runner after updated to v61.xx

### ISSUE THREAD

**Issue by mp3wizard** [Ashung/Automate-Sketch#228]
I found this issue with menu items name "Reset Overrides" and "Select all instances of Symbol"

**Comment by yorb** [comment]
The "Reset to Original…" (height, width, etc." are also missing after the update. Probably my most-used automate functions, would be great to see this fixed. :)

**Comment by dgmaia** [comment]
Yeah, there's something weird going on ... Most of the items inside Symbols are missing here...
