### ISSUE TITLE
Feature Request: Select all instances of a symbol on a page and rename

### ISSUE THREAD

**Issue by ryanbelisle** [Ashung/Automate-Sketch#23]
I'd love to see a command that would rename all instances of a selected symbol by page or document but not automatically name it to the master symbol, but a custom one.

**Example use:**
- Symbol name (in symbols page) is "Native App / Header / Search (Purple)"
- That symbol is used 100 times across the Sketch file
- In Page A - I'd like to select all the "Native App / header / Search (Purple)" symbols and give them a simple name like "app-header" on all symbol instances on that page.
- You could also apply "app-header" to ALL symbol instances in the entire document

**Comment by Ashung** [comment]
Add "Symbol" - "Custom Instances Name", please update plugin.

**Comment by ryanbelisle** [comment]
@Ashung This has been a lifesaver.... thank you so much!@!!@
