### ISSUE TITLE
Feature Request: Customisable toolbar items

### ISSUE THREAD

**Issue by edgeux** [Ashung/Automate-Sketch#239]
the only thing stopping me using this in ALL my workflows is the menu depth of some of the best functions. A configurable toolbar would be incredibly useful. I would gladly put some time in to developing some svg icons for this.

**Comment by Ashung** [comment]
You can use Runbar in Sketch Runner, but it's not available in free version.

**Comment by Arroyodorado** [comment]
You could also use this:
[https://github.com/sergeishere/HandyMenu-SketchPlugin](https://github.com/sergeishere/HandyMenu-SketchPlugin)
