### ISSUE TITLE
What happened to Paste and Replace

### ISSUE THREAD

**Issue by NirBenita** [Ashung/Automate-Sketch#24]
I love Cmd+alt+R! I could be confusing my plugins, but didn't you used to provide support for this?

I want to use this opportunity to tell you how much I love this project! It made my workflow much more powerful 🙏

**Comment by Ashung** [comment]
You need Paste and Replace?

**Comment by illustree** [comment]
that's about “Replace Layer” ... one of the hero functions of all time

**Comment by NirBenita** [comment]
Thanks for replying :)
The alternative is Cmd + Shift + V > Tab > Delete, so yeah 💯

**Comment by illustree** [comment]
please can you add the “Paste and Replace” function to “Automate”? that would be awesome!

**Comment by Ashung** [comment]
@NirBenita, @illustree 

Add "Layers" - "Paste and Replace".
Cmd + C, copy one Sketch layer, select any layers, run "Paste and Replace". 🎉

Add another "Utilities" - "Convert Sketch File to Other Version".
Convert Sketch file to old version, or open a high version file.

**Comment by bosha13** [comment]
Many thanks @Ashung! 👍

**Comment by illustree** [comment]
@Ashung crazy! made my day, thx
