### ISSUE TITLE
"Copy as X" Features don't work in Sketch 62

### ISSUE THREAD

**Issue by haenschenhans** [Ashung/Automate-Sketch#241]
Wanted to use the following commands:

Development |  
-- | --
Copy as PNG, PNG @2x, SVG | Copy seleceted layer as png, 2x png, svg.
Copy SVG Path Data | Copy SVG path data code from a selected shape layer.
Copy Slice as SVG Code | Copy SVG Code from selected slice layer.

but couldn't get them to work. Any requirements that the selected layer must meet to get this working?
Never tried it in other versions of Sketch before, but in v62 it seems to be broken.

Any help appreciated!

**Comment by Arroyodorado** [comment]
I'm using "Copy as PNG" a lot and it works as expected, also on Sketch 62. Simply select a layer / group / artboard, then select the command, then paste it somewhere else.
However there's a small bug: "Copy as PNG" copies as @2x and not @1x. Will notify Ashung about this… 8-)

**Comment by haenschenhans** [comment]
you're right it works now - but if I recall correctly, I had a Plugin Update from Sketch Automate this morning, so maybe it was fixed just now.

Anyways, will close the issue!
