### ISSUE TITLE
Feature Request: Move Artboard from Library to another Document (and keep symbols intact)

### ISSUE THREAD

**Issue by richardsison** [Ashung/Automate-Sketch#247]
Often I'll place instances of a symbol in the Sketch Library to test out the symbols. This process sometimes develops into complete sets of pages templates (because I don't have to worry about the lag between a Sketch File and a Sketch Library — while I'm building things out, I'm making a lot of small adjustments so this is faster).

Eventually I'll want to move these templates into a new document in the same project (within Abstract) but if I just copy and paste them over, Sketch creates new Local Symbols instead of mapping the Library Symbols.

What I do at the moment is use the merge duplicates plugin to map all of the local symbols to library symbols. This is ok, but feel it'd be better to be able to just move artboards from a library to a separate file.

**Comment by Ashung** [comment]
Add Library - Insert Artboard from Library
