### ISSUE TITLE
Feature request - Clean all Tints from all symbols in one command

### ISSUE THREAD

**Issue by krdesign** [Ashung/Automate-Sketch#249]
I'have updated Sketch 64, and a lot of my symbol have a "Tint" just setted because. 
Probably because i'have used function "copy and paste style" in pasts versions of sketch 64.1 Color tint on my symbols :(

**Comment by Ashung** [comment]
It is a Sketch bug. You can run the this code to remove all tints.

```
var sketch = require('sketch/dom');
var layers = [...sketch.find('Group'), ...sketch.find('SymbolInstance')]
layers.forEach(layer => {
  layer.style.fills = [];
});
```

**Comment by krdesign** [comment]
Thank you!
