### ISSUE TITLE
Feature Request: Removed unused symbols in external library

### ISSUE THREAD

**Issue by and0m** [Ashung/Automate-Sketch#251]
I love the Remove Unused Symbols feature but it will be great to extend it to do the same for external libraries.

My current workflow is 
Design Screens ... Create symbols...
Use the Remove Unused Symbols to delete all symbols from the file
Then I copy/paste all the symbols, which are left into an external file and use it as my library
Then I continue work in the file that holds just the screens but occasionally create new symbols, delete old ones, etc from the linked library
I remove some screens, etc
At this point my external library has many symbols which are unusued
I would like to go in the library and based on a file which holds my screens clean up the library
This could also work with other libraries in cases when I have a colours, fonts and symbols libraries in separate files.

I hope this could be done :)

**Comment by Ashung** [comment]
You can try this https://sleuth.keap.design.
