### ISSUE TITLE
Feature request: detach symbol and all its sub-symbols

### ISSUE THREAD

**Issue by josefrichter** [Ashung/Automate-Sketch#253]
Would it be possible to detach selected symbol and all its sub-symbols at the same time?

Typical use case: I have a symbol from Apple UI Library. When I detach it, its composed of several other symbols from that library, that I also need to detach. These are in turn composed of further symbols... So sometimes it's pretty tedious.

Would be nice to "break apart" the symbol with 1 command.

Thank you for considering it. You're doing a great job!

**Comment by Ashung** [comment]
Detach from Symbol  ⇧⌘Y
Detach all contents from Symbol  ⎇⇧⌘Y
