### ISSUE TITLE
Feature Request: Way to create ordered numbers for calendar

### ISSUE THREAD

**Issue by klin39** [Ashung/Automate-Sketch#257]
If there was a way to quickly populate symbols or rows of object with numbers ascending or descending, that would be super helpful when making a calendar month picker. Not sure what the best way to do it is, but it might need to take into consideration the XY position of the elements (instead of layer ordering).

Thanks!
Kevin Lin

**Comment by Ashung** [comment]
Layer - Data - Automate Sketch - Calendar
