### ISSUE TITLE
Feature Request: Convert artboards to symbols

### ISSUE THREAD

**Issue by ahmedlmahmoud** [Ashung/Automate-Sketch#260]
Hello Ashung,
I'm thankful to you for this amazing plugin! and your fast response/updates

Suggestion:
I'm suggesting a new option for converting artboards to symbols. 

The similar feature you have:
You have already a similar option "create a symbol from selected layer" but It's not converting the artboard. It's replacing the artboard with the instance for a symbol located automatically by sketch

Expected solution:
![Screen Recording 2020-04-30 at 6 19 06 AM 2020-04-30 06_20_11](https://user-images.githubusercontent.com/40777670/80671621-b4c36880-8aaa-11ea-8d9d-33f06b47dd23.gif)
I used Layer/Create Symbol option by sketch but I can't use it for bulk creation

**Comment by Ashung** [comment]
Add Symbol - Convert Artboards to Symbols
