### ISSUE TITLE
Feature Request: Update Styles of selected Text Layers

### ISSUE THREAD

**Issue by sirpooya** [Ashung/Automate-Sketch#262]
If I want to change the color of a Text Styles, I normally change it in the Text Layer linked to that style and then update that style, but it's not possible to do that to multiple layers at once.

A feature like "Update All Styles" or "Update Selected Text Layers" is very convenient in this case.

**Comment by Ashung** [comment]
Use Style - Update Style for Selected Layers, it support layer style and text style.
