### ISSUE TITLE
Feature Request: Bulk "Make Local"

### ISSUE THREAD

**Issue by jansemka** [Ashung/Automate-Sketch#263]
There is this neat feature from sketch (See screenshot below) where you can make external lib symbols local. Would be nice to have a bulk importer for this.

Background:
One of our designers used several libs to create a bigger project, now there are symbols all over the place from different Libs depricated, old versions and new ones. It is a mess. This feature would help to clean that up.

![image](https://user-images.githubusercontent.com/13254959/81063300-d7ed7e00-8ed7-11ea-9e9f-461d05836c4e.png)

**Comment by Ashung** [comment]
Add Library - Change Library Symbols to Local Symbol.
