### ISSUE TITLE
Style > Find and Replace Text Style library and style mismatch

### ISSUE THREAD

**Issue by jmcdermottsweeney** [Ashung/Automate-Sketch#280]
The names of the libraries in the dropdown do not correspond with the styles in that library. For example:

I am trying to merge local text styles with my library styles from Example_Library_1. The styles listed under the "Choose a style" dropdown are actually the styles coming from another library, Example_Library_2.

The command works properly, it just needs to be updated to reflect the proper library from the list of style options.

**Comment by ozgurgunes** [comment]
Hi. I fixed this in #293, hope gets merged soon.

**Comment by edullavin** [comment]
The Find and Replace Layer style and text styles seem to be working well for me. I sit possible to get the "Choose a style" dropdown to be organized alphabetically or however the "Find a style in this document" dropdown is ordered?
