### ISSUE TITLE
Feature Request: Clean up Paparazzi PDF

### ISSUE THREAD

**Issue by hobyvh** [Ashung/Automate-Sketch#29]
I have a request, probably an odd one, to automate the cleanup of PDFs output from the Paparazzi web capture tool. The reason is because it's tedious by hand and seems like it should be automate-able.

Steps to automate:
1. Find all groups with "Group" in the name and ungroup them
2. Find all layers that have "Clip" in the name and delete them
3. Find all text layers and move them 2px down
4. Create an artboard that matches the height and width of the document contents

Is that possible? I do this every time I need to work off of an existing web page and I currently do a lot of that.

**Comment by Ashung** [comment]
Step 1. Keep the group selected after import PDF.

Step 2. Run menu "Plugins" - "Run Script..." (before Sketch 45 this menu call "Custom Plugin..."), replace with these codes, then press "Run" button. 

``` javascript
var document = context.document;
var group = context.selection.firstObject();

// 4. Create an artboard that matches the height and width of the document contents
var artboard = MSArtboardGroup.alloc().init();
artboard.setRect(group.absoluteRect().rect());
artboard.frame().setConstrainProportions(false);
artboard.setName(group.name());
document.currentPage().addLayers([artboard]);
group.moveToLayer_beforeLayer(artboard, nil);
group.ungroup();

var loop = artboard.children().objectEnumerator();
while (layer = loop.nextObject()) {
    // 1. Find all groups with "Group" in the name and ungroup them
    if (layer.class() == "MSLayerGroup" && /Group\s\d+/.test(layer.name())) {
        layer.ungroup();
    }
    // 2. Find all layers that have "Clip" in the name and delete them
    if (layer.class() == "MSShapeGroup" && /Clip\s\d+/.test(layer.name())) {
        layer.removeFromParent();
    }
    // 3. Find all text layers and move them 2px down
    if (layer.class() == "MSTextLayer") {
        layer.frame().setY(layer.frame().y() + 2);
    }
}
```

3. If it works as you want, press "Save..." and give it a name, and your plugin will show in Plugins menu.

**Comment by hobyvh** [comment]
Sorry for the delay and thanks for posting this. I tried the script and the first error I get is:

> TypeError: null is not an object (evaluating 'group.absoluteRect') line: 7

I'm using Sketch 46.2

**Comment by Ashung** [comment]
Select a group first.

**Comment by hobyvh** [comment]
IT WORKS... and fast! Thanks again.
