### ISSUE TITLE
Create Color Variable from Layer Styles

### ISSUE THREAD

**Issue by downtowndesign** [Ashung/Automate-Sketch#290]
As your feature "Add color fills from Selected to Document Colors" doesn't work anymore since Sketch released Color Variables in V69 it would be great to create color variables from layer styles.

**Comment by Ashung** [comment]
"Add Colors from Selected Layers to Document" now support Sketch 69, use layer name as color name. 
If you have color variables with same name, you can choose update color variables or create new one.

**Comment by Ashung** [comment]
You can create color variables from text file, use [Import Colors V2](https://github.com/Ashung/import-colors-sketch).
