### ISSUE TITLE
Fill color from global & document colors feature is missing

### ISSUE THREAD

**Issue by nilstrieu** [Ashung/Automate-Sketch#292]
Is this missing temporary by mistake or do developers decide to remove it permanently?

**Comment by Ashung** [comment]
Sketch 69 remove global & document colors, you can press C to open Insert window, switch to color variables tab, drag and drop a color onto a layer.

**Comment by nilstrieu** [comment]
That's a sad news, an assigned keyboard shortcut is far more convenient. Btw, thank you for a great plugin.
