### ISSUE TITLE
“库替换”功能能否增加颜色的替换？

### ISSUE THREAD

**Issue by taycer** [Ashung/Automate-Sketch#296]
目前“库替换”可以替换替换控件，字符样式，图层样式；69版本新增的颜色样式，不知是否后续会在库替换里增加颜色的替换？
新功能颜色样式支持应用到图层的各种透明度里，避免了透明度多增加图层样式会出现很有很多个样式，所以sketch的这个颜色功能很好用，但是在替换库的时候目前没办法替换“颜色”，所以迫切希望增加此功能。

**Comment by Ashung** [comment]
加了，根据名称替换色彩，可以选择忽略名称前的序号。

可以使用 https://github.com/Ashung/import-colors-sketch 导出色彩成txt，修改色值之后在导入成只含色彩的库。
