### ISSUE TITLE
symbol api

### ISSUE THREAD

**Issue by feifeipan** [Ashung/Automate-Sketch#30]
Thanks a lot for generate selections to symbols.

I wanna try to write plugin to upload my symbol to my server. I search a lot, but api document is quite less. 

Could you please tell me where can i find these api? for example, how can i get the thumbnail of the selection?

**Comment by Ashung** [comment]
可以理解 Sketch 的 CocoaScript 是用 JavaScript 的语法同时写 JavaScript 和 Objective-C，来调用 Sketch 使用的 Cocoa 框架和 Sketch 内部类 [Sketch-Headers](https://github.com/abynim/Sketch-Headers)。所以有些文档在 [Apple 开发文档](https://developer.apple.com/documentation/)的 AppKit、Foundation、Objective-C 里面，比如文件读写。而有些文档则在 JavaScript 里面。

导出图层为图片，一般用 [MSDocument](https://github.com/abynim/Sketch-Headers/blob/master/Headers/MSDocument.h#L260-L263) 下的 `saveExportRequest_toFile` 或 `saveArtboardOrSlice_toFile`, [MSExportRequest](https://github.com/abynim/Sketch-Headers/blob/master/Headers/MSExportRequest.h#L29-L39)。

```javascript
var layer = context.selection.firstObject();

var exportRequest = MSExportRequest.exportRequestFromExportFormat_layer_inRect_useIDForName(
    MSExportFormat.alloc().init(), layer, layer.frame().rect(), false
);
exportRequest.setShouldTrim(false);
// exportRequest.setFormat("png");
// exportRequest.setScale(2);

context.document.saveExportRequest_toFile(exportRequest, "/Users/Ashung/Desktop/" + layer.name() + ".png");
```

**Comment by feifeipan** [comment]
谢谢🙏
