### ISSUE TITLE
RQ: Color variables symbol override

### ISSUE THREAD

**Issue by and0m** [Ashung/Automate-Sketch#301]
Hello,

currently the color variable replacement feature in the Libraries section works nicely when updating color variables from an external library. We would like to extend it in a way that updates the tint override color swatches for symbols.

USE CASE: 
Color library A with variables
Color library B with variables

Components library with layers, which are grouped, and have a tint color applied as a color variables from Color library A or B.

Master file where we build our designs using the components. 

At the moment if we replace the color variables using the plugin, it changes the color swatches which reference variables from Color Library A or B only for the layers in the file. The plugin doesn't apply these colors to the tint overrides swatches to the components which have been inserted from the Components library.

This will be really helpful to build dark/light mode.

The grouping and applying tint to groups is a workaround because Sketch doesn't support color variables override for imported symbols atm.

Thanks

**Comment by Ashung** [comment]
This a Sketch bug. You need to reset the default tint color override to the original color variable.

**Comment by and0m** [comment]
Thanks for the reply. Reset which default tint color? The one in components library or the master file? And reset it to which original color? Thanks for helping out. I'll send a ticket to sketch once i understand the limitations better.

**Comment by Ashung** [comment]
For example, you insert a symbol from library, and it have a color override (Library A - Color 1), you need to set the color to Library A - Color 1 or others, and plugin will replace this override.

**Comment by and0m** [comment]
Got it. Thanks.
