### ISSUE TITLE
Feature Request: Copy & Paste Layer X and/or Y Position 

### ISSUE THREAD

**Issue by troylend03** [Ashung/Automate-Sketch#305]
There was a plugin for this but no longer works properly and I didn't realize how reliant i was on it.
I used with Sketch Runner and it was so nice. 
Would be great to add into Automate

**Comment by jayliu50** [comment]
Is this similar to what you're looking for?

https://github.com/ajilderda/Sketch-Copy-Paste-Position-Size

I use this daily.

**Comment by troylend03** [comment]
Does it still work for you? it's been extremely inconsistent lately. 
Maybe bc I'm using Beta, but I literally relied on it all day and it's killing me not having it

**Comment by jayliu50** [comment]
It's been working flawlessly for me. I'm not on beta though
