### ISSUE TITLE
Resize and compress Images based on group dimensions

### ISSUE THREAD

**Issue by kilianso** [Ashung/Automate-Sketch#308]
We struggle a lot with huge filesizes if we import Sketch files into Figma because of big and uncompressed images.
So a really cool thing would be a mechanism that works similar to image transformation together `srcset` on the Frontend side. So based on the dimensions of the context/group the image gets resized and optimized on the fly and the original image will be replaced with the optimized one.

**Comment by Ashung** [comment]
File - Reduce File Size...
