### ISSUE TITLE
Layers/Rename Layers starts from bottom layer

### ISSUE THREAD

**Issue by jazzybeat** [Ashung/Automate-Sketch#309]
I was trying to use Layers/Rename Layers but quickly noticed that there is no option to specify the order of my layers. I have layers organized from Top to Botton but this feature renames layers from bottom to top. I t would be great if you could include an option to adjust the direction before running the script.

**Comment by Ashung** [comment]
{{n}} from bottom to top

**Comment by jazzybeat** [comment]
Thank you for your explanation. It's not entirely clear that N stands for reversed order. I think there is some room for improvement on the dialog screen. It would be simpler if you could provide an option to select the order using the dropdown menu.
