### ISSUE TITLE
Question: "Symbol>Sync Symbol Master from Sketch File" Usage

### ISSUE THREAD

**Issue by ipanema99** [Ashung/Automate-Sketch#31]
The plug-in is excellent -- thank you!

 "Symbol>Sync Symbol Master from Sketch File" is not working as I would expect. I'm not sure what the intended behavior is. Is it like this:
1. Select a symbol (Symbol X) in File A
2. Use "Symbol>Sync Symbol Master from Sketch File"; choose File B which also contains a symbol with the same symbol name (e.g. "Symbol X")
3. Symbol X in File A will now be updated to match Symbol X from File B

I've tried this, but it doesn't work. The originally selected symbol is removed from File A. Are there any requirements for symbol names in order for this to work properly?

Thanks,

Dave

**Comment by Ashung** [comment]
It replace symbols based on the Symbol ID, no the name.

**Comment by ipanema99** [comment]
OK -- I understand that Sync Symbol Master works using Symbol IDs (not symbol names).

However, it doesn't work with the attached example files. Each contain only 1 symbol (TestSymbolID), both with the Symbol ID AE7110FE-4EF9-4476-A132-57351A6A1EE2. Select the TestSymbolID symbol in "inherit.sketch" and choose "Sync Symbol Master"... choose the "master.sketch" file...the TestSymbolID symbol in "inherit.sketch" disappears. 

Any help would be appreciated -- thanks!

[Inherit_Master_Sketch.zip](https://github.com/Ashung/Automate-Sketch/files/1205779/Inherit_Master_Sketch.zip)

**Comment by Ashung** [comment]
Sketch 46 bug, I will fix it soon.

**Comment by Ashung** [comment]
@ipanema99 update v2.0.20170808

**Comment by ipanema99** [comment]
Wonderful -- thanks so much Ashung!
