### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by willcapellaro** [Ashung/Automate-Sketch#315]
Hi - I want to add default shortcuts to Automate Sketch so I don't have to use Apple's System Preferences. I always do this that way, but I had to reinstall Sketch recently and lost all of them.

I have a bunch of useful shortcuts that I think your users would like. I'll try forking and doing this myself. Can you point me to what file I'd need to modify to add the shortcuts?

**Comment by willcapellaro** [comment]
I'm making progress by working in the manifest file in my local Application Support directory. So I'm good for now—and will update when I have things working well.

**Comment by Ashung** [comment]
const menus = {
    "Plugins - Automate - Arrange - Change Places Between Two Objects": "ctrl shift t",
    "Plugins - Automate - Arrange - Change Places Between Two Objects (center)": "ctrl shift \u0020",
    "Plugins - Automate - Arrange - Tile Objects": "ctrl cmd →",
    "Plugins - Automate - Arrange - Tile Objects by Position X": "",
    "Plugins - Automate - Arrange - Tile Objects by Position Y": "",
    "Plugins - Automate - Arrange - Tile Objects Horizontally by Index": "",
    "Plugins - Automate - Arrange - Tile Objects Vertically by Index": "",
    "Plugins - Automate - Arrange - Distribute Layers Horizontally and Fit Width": "",
    "Plugins - Automate - Arrange - Distribute Layers Vertically and Fit Height": "",
    "Plugins - Automate - Arrange - Arrange Objects": "",
    "Plugins - Automate - Arrange - Order Layers By ... - Position X (Bottom-Top)": "",
    "Plugins - Automate - Arrange - Order Layers By ... - Position Y (Bottom-Top)": "",
    "Plugins - Automate - Arrange - Order Layers By ... - Position X (Top-Bottom)": "",
    "Plugins - Automate - Arrange - Order Layers By ... - Position Y (Top-Bottom)": "",
    "Plugins - Automate - Arrange - Order Layers By ... - Name": "",
    "Plugins - Automate - Arrange - Order Layers By ... - Kind": "",
    "Plugins - Automate - Arrange - Reverse Layer Order": "",
    "Plugins - Automate - Arrange - Collapse All Groups and Fit Canvas": "",
    "Plugins - Automate - Layer - Fit to Artboard with Margin": "",
    "Plugins - Automate - Layer - Fit to Parent with Margins": "",
    "Plugins - Automate - Layer - Fit to Parent Width with Margin": "",
    "Plugins - Automate - Layer - Fit to Parent Height with Margin": "",
    "Plugins - Automate - Layer - Swap Width and Height": "",
    "Plugins - Automate - Layer - Resize With Ratio": "",
    "Plugins - Automate - Layer - Adjust Sizes - Small Increase Width from Right": "",
    "Plugins - Automate - Layer - Adjust Sizes - Large Increase Width from Right": "",
    "Plugins - Automate - Layer - Adjust Sizes - Small Increase Width from Center": "",
    "Plugins - Automate - Layer - Adjust Sizes - Large Increase Width from Center": "",
    "Plugins - Automate - Layer - Adjust Sizes - Small Increase Height from Bottom": "",
    "Plugins - Automate - Layer - Adjust Sizes - Large Increase Height from Bottom": "",
    "Plugins - Automate - Layer - Adjust Sizes - Small Increase Height from Center": "",
    "Plugins - Automate - Layer - Adjust Sizes - Large Increase Height from Center": "",
    "Plugins - Automate - Layer - Adjust Sizes - Small Decrease Width from Right": "",
    "Plugins - Automate - Layer - Adjust Sizes - Large Decrease Width from Right": "",
    "Plugins - Automate - Layer - Adjust Sizes - Small Decrease Width from Center": "",
    "Plugins - Automate - Layer - Adjust Sizes - Large Decrease Width from Center": "",
    "Plugins - Automate - Layer - Adjust Sizes - Small Decrease Height from Bottom": "",
    "Plugins - Automate - Layer - Adjust Sizes - Large Decrease Height from Bottom": "",
    "Plugins - Automate - Layer - Adjust Sizes - Small Decrease Height from Center": "",
    "Plugins - Automate - Layer - Adjust Sizes - Large Decrease Height from Center": "",
    "Plugins - Automate - Layer - Bounds Layer for Every Selection": "",
    "Plugins - Automate - Layer - Divide Layer": "",
    "Plugins - Automate - Layer - Reset Bounding Box": "",
    "Plugins - Automate - Layer - Unlock All Layers": "",
    "Plugins - Automate - Layer - Show All Layers": "",
    "Plugins - Automate - Layer - Toggle Layer Constrain Proportions": "",
    "Plugins - Automate - Layer - Toggle Select Group’s Content on Click": "",
    "Plugins - Automate - Layer - Select Layers in Selection By Type - Groups": "",
    "Plugins - Automate - Layer - Select Layers in Selection By Type - Text Layers": "",
    "Plugins - Automate - Layer - Select Layers in Selection By Type - Shape Layers": "",
    "Plugins - Automate - Layer - Select Layers in Selection By Type - Images": "",
    "Plugins - Automate - Layer - Select Layers in Selection By Type - Symbol Instances": "",
    "Plugins - Automate - Layer - Select Layers in Selection By Type - Slices": "",
    "Plugins - Automate - Layer - Select Layers in Selection By Type - Exportable Layers": "",
    "Plugins - Automate - Layer - Select Layers in Selection By Type - Locked Layers": "",
    "Plugins - Automate - Layer - Select Layers in Selection By Type - Hidden Layers": "",
    "Plugins - Automate - Layer - Select Layers in Selection By Type - Transparency Layers": "",
    "Plugins - Automate - Layer - Select Layers By Name": "",
    "Plugins - Automate - Layer - Select All Child Layers": "",
    "Plugins - Automate - Layer - Select All Siblings Layers": "",
    "Plugins - Automate - Layer - Select Parent Groups": "",
    "Plugins - Automate - Layer - Select Layers Below": "",
    "Plugins - Automate - Layer - Select Layers Outside of Artboard Bounds": "",
    "Plugins - Automate - Layer - Select Reverse": "",
    "Plugins - Automate - Layer - Select None": "",
    "Plugins - Automate - Layer - Paste and Replace": "",
    "Plugins - Automate - Layer - Paste and Replace Setting": "",
    "Plugins - Automate - Layer - Copy Layer Position and Size": "",
    "Plugins - Automate - Layer - Paste Layer Position and Size": "",
    "Plugins - Automate - Layer - Paste Layer Position": "",
    "Plugins - Automate - Layer - Paste Layer Size": "",
    "Plugins - Automate - Layer - Remove Redundant Groups": "",
    "Plugins - Automate - Layer - Remove Empty Groups": "",
    "Plugins - Automate - Layer - Remove All Groups": "",
    "Plugins - Automate - Layer - Remove Hidden Layers": "",
    "Plugins - Automate - Layer - Remove Transparency Layers": "",
    "Plugins - Automate - Layer - Rename Layers": "",
    "Plugins - Automate - Layer - Find and Replace Layer Name": "",
    "Plugins - Automate - Layer - Clear Layer Name": "",
    "Plugins - Automate - Layer - Union Layer": "",
    "Plugins - Automate - Layer - Convert to Outlines": "",
    "Plugins - Automate - Layer - Toggle Mask for Selected Layers": "",
    "Plugins - Automate - Layer - Create Link Layer": "",
    "Plugins - Automate - Layer - Sync Link Layers": "",
    "Plugins - Automate - Symbοl - Reset to Original Width": "",
    "Plugins - Automate - Symbοl - Reset to Original Height": "",
    "Plugins - Automate - Symbοl - Reset to Original Size": "",
    "Plugins - Automate - Symbοl - Shrink Instance to Fit Content": "",
    "Plugins - Automate - Symbοl - Find and Replace Symbol": "",
    "Plugins - Automate - Symbοl - Reset Overrides": "",
    "Plugins - Automate - Symbοl - Disable or Enable All Overrides": "",
    "Plugins - Automate - Symbοl - Disable Selected Overrides": "",
    "Plugins - Automate - Symbοl - Selected Symbol Overrides to None": "",
    "Plugins - Automate - Symbοl - Select All Instances of Symbol": "",
    "Plugins - Automate - Symbοl - Select Same Instances in current Page": "",
    "Plugins - Automate - Symbοl - Rename Instances": "",
    "Plugins - Automate - Symbοl - Rename Instances Use Text Override": "",
    "Plugins - Automate - Symbοl - Create Symbols from Selected Layers": "",
    "Plugins - Automate - Symbοl - Selection to Symbol Master": "",
    "Plugins - Automate - Symbοl - Convert Artboards to Symbols": "",
    "Plugins - Automate - Symbοl - Detach All Symbols in Page or Artboard": "",
    "Plugins - Automate - Symbοl - Detach Unused Symbol Master": "",
    "Plugins - Automate - Symbοl - Remove Unused Symbols": "",
    "Plugins - Automate - Symbοl - Export All Symbols As PNG": "",
    "Plugins - Automate - Symbοl - Insert Symbols": "",
    "Plugins - Automate - Symbοl - Insert Instance of Selected Symbol": "",
    "Plugins - Automate - Symbοl - Sync Symbol Master from Sketch File base Symbol ID": "",
    "Plugins - Automate - Symbοl - Replace Pages with Same Name from Sketch File": "",
    "Plugins - Automate - Library - Fix Library ID Conflict": "",
    "Plugins - Automate - Library - Imported Symbols Link Manage": "",
    "Plugins - Automate - Library - Replace Library": "",
    "Plugins - Automate - Library - Fix Broken Library Symbols by Name": "",
    "Plugins - Automate - Library - Replace Symbol With Library Symbol": "",
    "Plugins - Automate - Library - Change Local Symbols to Library Symbol": "",
    "Plugins - Automate - Library - Change Library Symbols to Local Symbol": "",
    "Plugins - Automate - Library - Swap Color Variables from Library": "",
    "Plugins - Automate - Library - Change Local Text Style to Library Text Style": "",
    "Plugins - Automate - Library - Change Local Layer Style to Library Layer Style": "",
    "Plugins - Automate - Library - Import Styles from Library": "",
    "Plugins - Automate - Library - Import Document Assets from Library": "",
    "Plugins - Automate - Library - Add Library Preview": "",
    "Plugins - Automate - Library - Insert Symbols from Library": "",
    "Plugins - Automate - Library - Insert Artboard from Library": "",
    "Plugins - Automate - Library - Update Selected Library Symbol": "",
    "Plugins - Automate - Library - Update Selected Symbol Overrides": "",
    "Plugins - Automate - Library - Check For Library Updates": "",
    "Plugins - Automate - Library - Update Imported Objects from Library": "",
    "Plugins - Automate - Artboard - Paste as Artboards": "",
    "Plugins - Automate - Artboard - Paste as Symbol Masters": "",
    "Plugins - Automate - Artboard - Artboard from Selection": "",
    "Plugins - Automate - Artboard - Artboard from Group": "",
    "Plugins - Automate - Artboard - Artboard To Group": "",
    "Plugins - Automate - Artboard - Select Parent Artboard": "",
    "Plugins - Automate - Artboard - Artboard Navigator": "",
    "Plugins - Automate - Artboard - Resize to Fit Width": "",
    "Plugins - Automate - Artboard - Resize to Fit Height": "",
    "Plugins - Automate - Artboard - Toggle Adjust Content on Resize": "",
    "Plugins - Automate - Artboard - Move Artboards to Bottom of Another": "",
    "Plugins - Automate - Artboard - Move to Page": "",
    "Plugins - Automate - Artboard - Group Selected Layers in Each Artboard": "",
    "Plugins - Automate - Artboard - Export All Artboards": "",
    "Plugins - Automate - Artboard - Export All Artboards to HTML": "",
    "Plugins - Automate - Style - Select Layers by Layer Style": "",
    "Plugins - Automate - Style - Select Layers by Text Style": "",
    "Plugins - Automate - Style - Select Layers With Same Shared Style": "",
    "Plugins - Automate - Style - Paste Fills": "",
    "Plugins - Automate - Style - Paste Borders": "",
    "Plugins - Automate - Style - Paste Shadows": "",
    "Plugins - Automate - Style - Paste Inner Shadows": "",
    "Plugins - Automate - Style - Paste Blur": "",
    "Plugins - Automate - Style - Paste Text Style": "",
    "Plugins - Automate - Style - Paste Text Color": "",
    "Plugins - Automate - Style - Paste Text Font": "",
    "Plugins - Automate - Style - Add Solid Fill from CSS Color": "",
    "Plugins - Automate - Style - Swap Fill and Border": "",
    "Plugins - Automate - Style - Remove All Disabled Styles": "",
    "Plugins - Automate - Style - Remove Unused Layer Styles": "",
    "Plugins - Automate - Style - Remove Unused Text Styles": "",
    "Plugins - Automate - Style - Update Style for Selected Layers": "",
    "Plugins - Automate - Style - Reset Style for Selected Layers": "",
    "Plugins - Automate - Style - Reset All Layer Styles": "",
    "Plugins - Automate - Style - Reset All Text Styles": "",
    "Plugins - Automate - Style - Find and Replace Layer Style": "",
    "Plugins - Automate - Style - Find and Replace Text Style": "",
    "Plugins - Automate - Style - Merge Local Layer Styles with Same Name": "",
    "Plugins - Automate - Style - Merge Local Text Styles with Same Name": "",
    "Plugins - Automate - Style - Change Layer Blend Mode": "",
    "Plugins - Automate - Style - Create Color Guide": "",
    "Plugins - Automate - Style - Create Style Guide": "",
    "Plugins - Automate - Style - Create Typography Guide": "",
    "Plugins - Automate - Style - Convert to Color Variable": "",
    "Plugins - Automate - Style - Add Styles from Selected Layers": "",
    "Plugins - Automate - Style - Add Colors or Gradients from Selected to Document": "",
    "Plugins - Automate - Style - Import Document Assets from Sketch File": "",
    "Plugins - Automate - Style - Import Text Styles from Sketch File": "",
    "Plugins - Automate - Style - Import Layer Styles from Sketch File": "",
    "Plugins - Automate - Guide - Grid Presets": "",
    "Plugins - Automate - Guide - Copy Grid": "",
    "Plugins - Automate - Guide - Paste Grid": "",
    "Plugins - Automate - Guide - Copy Layout": "",
    "Plugins - Automate - Guide - Paste Layout": "",
    "Plugins - Automate - Guide - Remove Layouts": "",
    "Plugins - Automate - Guide - Copy Guide": "",
    "Plugins - Automate - Guide - Paste Guide": "",
    "Plugins - Automate - Guide - Clear Guides": "",
    "Plugins - Automate - Guide - New Guide": "",
    "Plugins - Automate - Guide - New Guide Layout": "",
    "Plugins - Automate - Guide - New Guides from Layer": "",
    "Plugins - Automate - Guide - Hide or Show All Grid": "",
    "Plugins - Automate - Guide - Hide or Show All Layout": "",
    "Plugins - Automate - Text - Change Texts": "",
    "Plugins - Automate - Text - Paste as Alphabetical Order Text": "",
    "Plugins - Automate - Text - Increase Line Height": "",
    "Plugins - Automate - Text - Decrease Line Height": "",
    "Plugins - Automate - Text - Increase Letter Spacing": "",
    "Plugins - Automate - Text - Decrease Letter Spacing": "",
    "Plugins - Automate - Text - Increase Horizontally Scale": "",
    "Plugins - Automate - Text - Decrease Horizontally Scale": "",
    "Plugins - Automate - Text - Reset Horizontally Scale": "",
    "Plugins - Automate - Text - Not Truncate Text": "",
    "Plugins - Automate - Text - Truncate Text at Start": "",
    "Plugins - Automate - Text - Truncate Text at Middle": "",
    "Plugins - Automate - Text - Truncate Text at End": "",
    "Plugins - Automate - Text - Split Text Layer": "",
    "Plugins - Automate - Text - Combine Text Layers": "",
    "Plugins - Automate - Text - Capitalize": "",
    "Plugins - Automate - Text - Change Text Orientation": "",
    "Plugins - Automate - Text - Change Typeface for Latin Character": "",
    "Plugins - Automate - Text - Add Space Between CJK and Latin Character": "",
    "Plugins - Automate - Text - Increase Font Weight": "",
    "Plugins - Automate - Text - Decrease Font Weight": "",
    "Plugins - Automate - Text - Replace Fonts": "",
    "Plugins - Automate - Text - Resize to Fit Text Height": "",
    "Plugins - Automate - Text - Toggle Auto and Fixed": "",
    "Plugins - Automate - Text - Fixed Layer Name": "",
    "Plugins - Automate - Text - Unfixed Layer Name": "",
    "Plugins - Automate - Text - Character Count": "",
    "Plugins - Automate - Slice - Quick Export (Default)": "",
    "Plugins - Automate - Slice - Quick Export (Preset 1)": "",
    "Plugins - Automate - Slice - Quick Export (Preset 2)": "",
    "Plugins - Automate - Slice - Quick Export Setting": "",
    "Plugins - Automate - Slice - Auto Slice": "",
    "Plugins - Automate - Slice - Fast Slice": "",
    "Plugins - Automate - Slice - Slice Setting": "",
    "Plugins - Automate - Slice - Remove All Slices": "",
    "Plugins - Automate - Slice - Clear All Exportables": "",
    "Plugins - Automate - Slice - Divide Slice": "",
    "Plugins - Automate - Slice - Save Export Presets": "",
    "Plugins - Automate - Slice - Load Export Presets": "",
    "Plugins - Automate - Data - Copy Text from Layer": "",
    "Plugins - Automate - Data - Copy Text from Override": "",
    "Plugins - Automate - Data - Export Data from Text Layers": "",
    "Plugins - Automate - Data - Export Image from Layers": "",
    "Plugins - Automate - Data - Export Data from Symbol Instances": "",
    "Plugins - Automate - Prototyping - Bring All Hotspot to Front": "",
    "Plugins - Automate - Prototyping - Reset Flow": "",
    "Plugins - Automate - Prototyping - Remove All Hotspot": "",
    "Plugins - Automate - Prototyping - Remove Hotspot in Selected Artboards": "",
    "Plugins - Automate - Development - Copy as PNG": "",
    "Plugins - Automate - Development - Copy as PNG @2x": "",
    "Plugins - Automate - Development - Copy as SVG": "",
    "Plugins - Automate - Development - Copy as SVG (URL-encoded)": "",
    "Plugins - Automate - Development - Copy as Path Data": "",
    "Plugins - Automate - Development - Copy as Base64": "",
    "Plugins - Automate - Development - Export Artboard to ICNS File": "",
    "Plugins - Automate - Development - Pick Color and Copy the HEX Code": "",
    "Plugins - Automate - Development - Copy Selected Layer Name": "",
    "Plugins - Automate - Development - Copy Object ID or Symbol ID": "",
    "Plugins - Automate - Development - Show and Change Layer Info": "",
    "Plugins - Automate - Development - Change Document ID": "",
    "Plugins - Automate - Development - Plugin Dev Setting": "",
    "Plugins - Automate - Development - Reload Plugins": "",
    "Plugins - Automate - Utilities - Copy Document URL": "",
    "Plugins - Automate - Utilities - Shortcuts Manager": "",
    "Plugins - Automate - Utilities - Insert Layer from SVG Path Data": "",
    "Plugins - Automate - Utilities - Export Clean Code SVG": "",
    "Plugins - Automate - Utilities - SVG Export Setting": "",
    "Plugins - Automate - Utilities - Nine-Slice from Bitmap Layer": "",
    "Plugins - Automate - Utilities - Open Terminal at File Folder": "",
    "Plugins - Automate - Utilities - Switch Language": "",
    "Plugins - Automate - Help - Web Site": "",
    "Plugins - Automate - Help - Change Log and Old Versions": "",
    "Plugins - Automate - Help - Report Issue": "",
    "Plugins - Automate - Help - Disable Google Analytics": "",
    "Plugins - Automate - Help - Donate": ""
};

const KEY_VALUES = {
    'cmd': '@',
    'alt': '~',
    'ctrl': '^',
    'shift': '$',
    // '⌫': '\u0008',
    // '⇥': '\u0009',
    // '↩': '\u000d',
    // '⎋': '\u001b',
    // '←': '\u001c',
    // '→': '\u001d',
    // '↑': '\u001e',
    // '↓': '\u001f',
    // '⌦': '\u007f',
    // '↖': '\u2196',
    // '↘': '\u2198',
    // '⇞': '\u21de',
    // '⇟': '\u21df'
};

let shortcuts = NSMutableDictionary.alloc().init();

Object.keys(menus).forEach(menu => {
    let value = menus[menu];
    if (value !== '') {
        let key = '\u001b' + menu.replace(/ - /g, '\u001b');
        Object.keys(KEY_VALUES).forEach(k => {
            value = value.replace(k, KEY_VALUES[k]);
        });
        shortcuts.setValue_forKey(value, key);
    }
});

var userDefaults = NSUserDefaults.standardUserDefaults();
userDefaults.setObject_forKey(shortcuts, "NSUserKeyEquivalents");
userDefaults.synchronize();

// var manifest = require("/Users/hongsisheng/Projects/Automate-Sketch/automate-sketch.sketchplugin/Contents/Sketch/manifest.json");

// let json = {};
// manifest.menu.items.forEach(group => {
//   group.items.forEach(item => {
//     if (item != "-" && typeof item == "string") {
//       let title = manifest.commands.find(cmd => {
//         return cmd.identifier === item
//       }).name;
//       // console.log(`${group.title} - ${title}`)
//       json[`Plugins - Automate - ${group.title} - ${title}`] = ''
//     }
//     if (item instanceof Object) {
//       item.items.forEach(_item => {
//         if (_item != "-" && typeof _item == "string") {
//           let title = manifest.commands.find(cmd => {
//             return cmd.identifier === _item
//           }).name;
//           // console.log(`${group.title} - ${item.title} - ${title}`);
//           json[`Plugins - Automate - ${group.title} - ${item.title} - ${title}`] = ''
//         }
//       })
//     }
//   })
// });

// log(JSON.stringify(json, null, 4))

**Comment by Ashung** [comment]
This script include all commands in Automate, you can custom shortcut by change the value. https://developer.sketch.com/plugins/plugin-manifest#shortcut-values

```
const menus = {
    "Plugins - Automate - Arrange - Change Places Between Two Objects": "ctrl shift t",
    "Plugins - Automate - Arrange - Change Places Between Two Objects (center)": "ctrl cmd →",
    "Plugins - Automate - Arrange - Tile Objects": "",
```

Run this script in "Sketch" - "Plugin" - "Run Script" dialog, it will replace all you Automate shortcuts in OS System Preferences.

**Comment by willcapellaro** [comment]
Thanks Ashung!

**Comment by willcapellaro** [comment]
So that didn't work for me, and it would be good to avoid messing with System Preferences. I'm just going to keep a list of items to update in the manifest. But it would be great if we could have our own file that loads - we can drop it in after updating the plug in. It would be great to have to have the shortcuts survive updating though.
