### ISSUE TITLE
使用快速切片功能后   切片位置会偏移至整个画板外

### ISSUE THREAD

**Issue by Eashare** [Ashung/Automate-Sketch#316]
目前SKTCH的版本是72.1  包括71.1     自动化版本为  72.0.20210508  
控件页面  选中画板内的文件夹或者单一图层  **使用快速切片功能后   切片位置会偏移**
切片位置会自动偏移至画板外   比如本来画板XY轴位置是 12   ；   89     快速切片后生成的切片位置会变成-12 -89   
同事电脑也这样   网友小伙伴最近都出现了这个问题

_直接选中整个画板使用快速切片 位置就正常_

**Comment by jiaye-saoqi** [comment]
我也是，麻烦请快点修复
