### ISSUE TITLE
Select layers by type > Locked layers

### ISSUE THREAD

**Issue by saadchdhry** [Ashung/Automate-Sketch#317]
Hi, 

Can we have `Layer` > `Select Layers in Selection by Type` > `Locked layers` to select all the locked layers ?

![Screenshot 2021-05-26 at 12 32 40](https://user-images.githubusercontent.com/5164457/119637585-7bc90500-be1e-11eb-9986-82725748a13f.png)

Thanks!

**Comment by Ashung** [comment]
Update new version.
