### ISSUE TITLE
Feature Request: Butt layers together

### ISSUE THREAD

**Issue by everydayslang** [Ashung/Automate-Sketch#318]
I very useful plugin, Butter, has broken with a recent sketch update as seem to no longer be supported. Both Automate and Sketch's "Tidy" button come close to this functionality, but don't quite address my need. I'd love if Automate was able to add this as a feature 💕

https://github.com/pberrecloth/butter-sketch-plugin

**Comment by Ashung** [comment]
Use Arrange - Tile Objects
