### ISSUE TITLE
“paste and replace” symbol (not existing in a document) fails

### ISSUE THREAD

**Issue by illustree** [Ashung/Automate-Sketch#32]
“Symbol master “symbol name” can't found in current document.”
... this message shows up when you try to replace from one to another document.

Expected result: it would just replace and place masters into the new document. Please can you fix?
many thanks

**Comment by Ashung** [comment]
@illustree I will fix it tomorrow, now you can copy the symbol master to your document first.

**Comment by Ashung** [comment]
@illustree update v46.1.20170810, if you copy a symbol instance from document A, and run "paste and replace" in document B, the symbol will add/update to document B.
You can also copy a symbol master A from document A, and run "paste and replace" in document B, while select symbol master B, all instances of symbol master B will be replaced.

**Comment by illustree** [comment]
Hey, thanks for that fast update! but still an issue there ... it is doing now the following ... empty error symbols :---( can you please check again?
https://www.dropbox.com/s/tk7gtto1ygctxol/Screenshot%202017-08-10%2009.14.16.png?dl=0

**Comment by Ashung** [comment]
I can't open the image, why upload as attachment.

**Comment by illustree** [comment]
![screenshot 2017-08-10 09 14 16](https://user-images.githubusercontent.com/20769270/29166942-b600905c-7dc8-11e7-9417-e3fa2991550b.png)
