### ISSUE TITLE
Feature request: Change local color variables to library color variables

### ISSUE THREAD

**Issue by danieliustv** [Ashung/Automate-Sketch#327]
It would be great if it would be possible to swap local color variables to the ones from the library.
Thanks for the best Sketch plugin ever that literally saves hours!

**Comment by Ashung** [comment]
Library - Swap Color Variables from Library

**Comment by danieliustv** [comment]
Thanks, it doesn't work the same as with styles as the local variables remain in the document, is there a way to make it remove local ones after a change?
