### ISSUE TITLE
Feature request: center group content

### ISSUE THREAD

**Issue by illustree** [Ashung/Automate-Sketch#34]
what I am missing so often is a quick way to center group content depending on the lowest layer in the group. Or a layer called “bg” or “BG”

The command could go into: ARRANGE / center group content

**Comment by Ashung** [comment]
You open "View" - "Canvas" - "Show Smart Guides"?

**Comment by illustree** [comment]
yes, I have that checked of course, but a defined shortcut is always faster ... I always used that feature from dynamic reposition until the plugin stopped working

**Comment by Ashung** [comment]
Dynamic Reposition seem not under maintain, you can use [Resizing Constraints](https://www.sketchapp.com/learn/documentation/layer-basics/constraints/#float-in-place-and-fix-padding) instead.

**Comment by illustree** [comment]
:---) that's not solving my request, which was about having a shortcut for centering ... not via mouse and clicks... but ok thanks, forget it ... will look for another option
