### ISSUE TITLE
Bug: Paste and Replace pastes doesn't paste into the selected artboard anymore

### ISSUE THREAD

**Issue by richardsison** [Ashung/Automate-Sketch#35]
When I execute paste and replace it doesnt paste into the selected artboard anymore. The position is correct, but not the location.

Also, can you update the functionality to be able to copy and paste from the global clipboard and not just from within Sketch? 

I sometimes edit an image in Pixelmator or Photoshop and have to paste it in Sketch before I'm able to Paste and Replace.

**Comment by Ashung** [comment]
Update v46.1.20170811, now can paste image from Pixelmator, Photoshop, Illustrator, Affinity Designer or clipboard. 

You can't paste into the selected artboard, it will remove artboard. I planning to add a feature like Paste into Artboards.

**Comment by richardsison** [comment]
Awesome! Thanks @Ashung!
