### ISSUE TITLE
Fix pasting in Artboard 👉🏼 Move to page

### ISSUE THREAD

**Issue by carlotademier** [Ashung/Automate-Sketch#351]
When using the functionality Artboard 👉🏼 Move to page, pasting is not equal than in the page that the artboards or symbols where before. They get pasted in vertical order (first screenshot named "Pasting" The idea is to paste them in the same order that they were in the previous page (second screenshot named Previous page)

<img width="1424" alt="Pasting" src="https://user-images.githubusercontent.com/105039773/167084366-4b1e5604-6ef4-4f3f-a534-abbe7e33bf90.png">

<img width="1425" alt="Previous page" src="https://user-images.githubusercontent.com/105039773/167084377-c9bd659d-98b5-443f-bbb8-0fd7736e43d2.png">

**Comment by Ashung** [comment]
Use drag the artboard  to page name.

**Comment by carlotademier** [comment]
Hi @Ashung , thanks very much for your reply but I can't find this option. Could you tell me the path in the plugin to find it please?

**Comment by Ashung** [comment]
![s](https://user-images.githubusercontent.com/932544/167578087-6d4ce046-5c47-41af-8b36-99d9cacd241f.gif)

**Comment by Ashung** [comment]
![s](https://user-images.githubusercontent.com/932544/167578087-6d4ce046-5c47-41af-8b36-99d9cacd241f.gif)

**Comment by Ashung** [comment]
![s](https://user-images.githubusercontent.com/932544/167578087-6d4ce046-5c47-41af-8b36-99d9cacd241f.gif)

**Comment by carlotademier** [comment]
Thanks a lot!
