### ISSUE TITLE
[BUG] select parent group(s) doesn't work on multiple selection

### ISSUE THREAD

**Issue by RaphyRaph** [Ashung/Automate-Sketch#38]
Right now, it only selects one the parents, like this:
https://www.dropbox.com/s/c045e3b1c54z91i/parent%20group.mov?dl=0

It should work like this:
- Select parent group should select *all* the parents of multiple selection. 
- If your selection contains a child of the other one, you need to select the highest parent.
![slice](https://user-images.githubusercontent.com/3810802/29276202-bd4f714e-8105-11e7-88f7-8fdd6933f65f.png)

**Comment by Ashung** [comment]
@RaphyRaph I fixed it, update the new version.
