### ISSUE TITLE
paste and replace breaks/shifts Auto-Layout's Stacked Groups

### ISSUE THREAD

**Issue by illustree** [Ashung/Automate-Sketch#39]
Hi there, to reproduce: create a stacked group, then just replace one of the elements ... if I use the “replace layer” from Sketch Mate - it does how it should be ... can you please fix? because I really want to use your “replace” as it's better

**Comment by RaphyRaph** [comment]
This happens to me too! Please fix 💕
- Screen-capture of the issue: [https://www.dropbox.com/s/...](https://www.dropbox.com/s/jzqozt767g9at6a/paste%20replace%20and%20auto%20layout.mov?dl=0)
- Link to the auto-layout plugin: https://github.com/animaapp/auto-layout

**Comment by timdose** [comment]
I ran into this as well!

I think this same issue was causing some weird group bounding boxes whenever you used Paste and Replace. It also apparently drives Auto Layout bonkers.

@Ashung I was able to find a fix by adding this on line 49 of 'Paste_and_Replace.cocoascript':
`oldLayer.parentGroup().resizeToFitChildrenWithOption(1); `

I don't have time to make a pull request for this right now, but I'll try to make one in the next couple days.

**Comment by timdose** [comment]
Oh, wait—that doesn't seem to solve it in all cases. It does seem to have something to do with improper group sizing after Paste and Replace.

**Comment by tim-dose-zocdoc** [comment]
This seems to be fixed in the latest update!

@Ashung thanks so much!!!

**Comment by RaphyRaph** [comment]
Niiiiice!
