### ISSUE TITLE
Remove Unused Symbols

### ISSUE THREAD

**Issue by warb2n** [Ashung/Automate-Sketch#4]
If U can fix this in your plugin, it will be awesome…

[**Problem**](https://github.com/sketchplugins/remove-unused-symbols/issues/1)

**Comment by sonburn** [comment]
I think you might still have an issue. I am exploring your work for my own purposes, and noticing an override I have applied is somehow in a dictionary called "__NSSingleEntryDictionaryI", therefore it's not getting noticed since you are only checking "__NSDictionaryI" and "__NSDictionaryM". I think you might need to check for a class of "__NSSingleEntryDictionaryI" as well, and possibly "__NSSingleEntryDictionaryM" (not sure what the distinction is)?

**Comment by sonburn** [comment]
Also, unrelated to overrides, are you not finding that your plugin will still delete symbols if they are nested in some parent symbol, and that parent symbol has no instances of it's own? I think some additional logic needs to be added to look for symbols with nested symbol instances, and add those nested symbol instance IDs to your list of exemptions as well. I am currently working on this for my purposes, if I figure it out, I will pass along the solution.

**Comment by sonburn** [comment]
I got it working in my plugin [Symbol Organizer](https://github.com/sonburn/symbol-organizer). Hopefully this helps you...

`// If child is a symbol instance and has overrides...
if (child.class() == "MSSymbolInstance" && child.overrides()) {
    // Create object of overrides
    var overrides = child.overrides().objectForKey(0).allValues();

    // Iterate through overrides
    for (var i = 0; i < overrides.count(); i++) {
        // Function to add each override symbol ID to exempt symbols object
        pushOverrideSymbolIDtoArray(overrides.objectAtIndex(i),idsOfSymbolInOverrides);
    }
}

// If child is a symbol master...
if (child.class() == "MSSymbolMaster") {
    // Layer variables
    var layers = child.children();
    var loopLayers = layers.objectEnumerator();
    var layer;
    var exemptions = 0;

    // Iterate through layers
    while (layer = loopLayers.nextObject()) {
        // If layer is a symbol instance...
        if (layer.class() == "MSSymbolInstance") {
            // Add symbol master ID to exempt symbols object
            idsOfSymbolInOverrides.push(String(layer.symbolMaster().symbolID()));

            // Increment exemption counter
            exemptions++;
        }
    }

    // If this symbol had nested symbols...
    if (exemptions > 0) {
        // Add this symbol ID to exempt symbols object
        idsOfSymbolInOverrides.push(String(child.symbolID()));
    }
}`

**Comment by Ashung** [comment]
Thank you.  i add a checkbox that can choose remove nested symbols or not.
