### ISSUE TITLE
“Paste and Replace” creates duplicates on the symbols page

### ISSUE THREAD

**Issue by illustree** [Ashung/Automate-Sketch#40]
please - can you fix that?
thanks in advance!!!

**Comment by illustree** [comment]
same thing is reported here https://github.com/getflourish/Sketch-Mate/issues/39

**Comment by Ashung** [comment]
I use Sketch 46.2 , it never create duplicates symbol master while the symbol has same ID.

If you have duplicated symbols, select the symbol and run "Automate" - "Symbol" - "Select All Instances of Symbol", then run "Replace With" from right-click menu.

**Comment by illustree** [comment]
hi there, that unfortunately doesn't solve the issue ... for duplicates created by Automate and also Mate currently I use the Plugin “Merge duplicate symbols”
