### ISSUE TITLE
Feature Request: Resize Height of Textfield to Fit

### ISSUE THREAD

**Issue by Arroyodorado** [Ashung/Automate-Sketch#41]
When a textfield is set to "fixed" mode its height follows whatever is the content of the textfield. However once you change the height of the textfield manually it stays like that disregarding of what is its content and there is currently no way to get back the previous behaviour. I guess this came with Sketch 45 or 46.

Is there any way to reset the height of a textfield to fit its content via script?

And thanks so much for yopur plugin, I use it a lot!

**Comment by Ashung** [comment]
Keep the width of textfield, and resize height to fit textfield?

**Comment by Arroyodorado** [comment]
Yes, exactly.

**Comment by Ashung** [comment]
@Arroyodorado, I add the feature, you can find it in menu "Automate" - "Type" - "Resize to Fit Text Height".

**Comment by Arroyodorado** [comment]
@Ashung Thanks for adding this feature. I tested it and it works fine. Well, almost... I think one step is missing: 

In your script after line 59 `layer.frame().setWidth(originalWidth);`

there should be `layer.setTextBehaviour(1);`

Because before calling your function, text behaviour was "fixed" and it should still be "fixed" after the execution. Right now it is set to "Auto" which I understand is necessary to reset the height. But I have to click on the "Fixed" button in the inspector again to get what I was looking for. Adding this line would make it perfect.

And thank you one more time for your whole suite of functions! I use them a lot. 8-)

Best Regards!
