### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by RaphyRaph** [Ashung/Automate-Sketch#44]
select library symbol instances (not local ones)

**Comment by jardicc** [comment]
[FR] quick precise zoom
- like if you hold Ctrl + Shift + Alt + Mouse scroll in Photoshop
- current Sketch mouse scrool zoom is slow and pixel inperfect
- current Sketch shortcut for zoom Command + "+" zooms in canvas center or select layer center
- predefined zooming steps 10% 33% 50% 67% 100% 200% 300% 400% 800% 1600% 3200%
- zoom would be centered to the current cursor position

**Comment by Ashung** [comment]
@jardicc I'm so sorry, current version of Sketch can not custom zoom steps in plugins. 

If you need center selected layers after press shortcut cmd + "-/+",  goto "Sketch" - "Preferences" - "Canvas", and checked the "Zoom in on Selection"

**Comment by jardicc** [comment]
Hmm interesting. I tried this settings but it is even worse. I will probably try next year custom plugin. In Photoshop I was able to create scripts considered as impossible. Maybe I will have luck with Sketch plugins.

**Comment by jardicc** [comment]
Today I created the plugin which does what I want. The last thing I need is to know if there is a way how to execute plugin on mouseScrollEvent + modifier keys pressed.
