### ISSUE TITLE
Fix to Parent Width + Height (without margins)

### ISSUE THREAD

**Issue by avirambo** [Ashung/Automate-Sketch#45]
Hi, Your plugin is PERFECT!
if the fix to parent will have another option to fix ti width AND height together it will be super helpful! and in that case it could be even better without the margins, just to create objects and instantly make them the "background" of an group or artboard. 
Thank you so much!

**Comment by Ashung** [comment]
@avirambo add Fix to Parent with Margin, you can use 0 for without margins.
