### ISSUE TITLE
Not seeing menu option to Change symbols to Library Symbol

### ISSUE THREAD

**Issue by mrengy** [Ashung/Automate-Sketch#46]
Thanks for the contribution.

On the readme, I saw the item "Change symbols to Library Symbol", described as "Change the selected/all symbols to library symbol base on symbol ID.". This sounds like what I want to do in order to resolve [this problem](https://graphicdesign.stackexchange.com/q/101062/53953). 

But I'm not seeing this as an option from within the Sketch (version 47.1) menu. Here's what I see:
![screen shot 2017-11-08 at 10 46 51 am](https://user-images.githubusercontent.com/2223603/32558368-9261ff6e-c472-11e7-9efd-ac6449ebc55c.png)

How do I use this feature?

**Comment by Ashung** [comment]
@mrengy you may use a old version plugin, the latest version is 47.1.20171025.
It is better to use Automate with [Sketch Runner](http://sketchrunner.com/).

For you problem, if you want to change symbol base the layer name, you can use [library-symbol-replacer](https://github.com/zeroheight/library-symbol-replacer) or [symbol-swapper](https://github.com/sonburn/symbol-swapper).
