### ISSUE TITLE
文本框默认焦点位置建议。

### ISSUE THREAD

**Issue by yanghaoleng** [Ashung/Automate-Sketch#49]
在 Select layers in selection by name 功能里，希望吧默认焦点位置放在 layer name 文本输入框里头。

这是一个我非常常用的功能。但是每次都需要鼠标点一下修改名称。
谢谢！

**Comment by Ashung** [comment]
激活图层名的编辑状态这个可能做不到，如果你需要改名，可以在选中之后用 [RenameIt](https://github.com/rodi01/RenameIt) 插件。很多人选择并不是要改图层名。

**Comment by yanghaoleng** [comment]
对不起我之前表达有歧义，Select layers in selection by name 这个功能不是有一个弹窗嘛，弹窗第一个要输入框，输入要查找的图层名称，就是希望默认的焦点放在这个输入框上面...目前默认焦点在取消按钮上。

**Comment by Ashung** [comment]
新版已修改。
