### ISSUE TITLE
Feature Request: Remove all redundant groups

### ISSUE THREAD

**Issue by edenvidal** [Ashung/Automate-Sketch#5]
Not sure if this is the right way to call it, but what I mean is to delete all nested groups which are unnecessary.
See example:
![screen shot 2016-12-21 at 12 12 34 pm](https://cloud.githubusercontent.com/assets/13418616/21385351/d382dd82-c776-11e6-9f8c-4c4f259ca7fd.png)

**Comment by Ashung** [comment]
Add "Layer" - "Remove Redundant Groups".
If select artboards or groups, it will remove all redundant groups in selected artboards or groups.
If select nothing, it will remove all redundant groups in current page.
