### ISSUE TITLE
Imported Symbols Link Manage loses overrides

### ISSUE THREAD

**Issue by maxvoltar** [Ashung/Automate-Sketch#53]
Like the title says. I'm not sure it is technically possible to keep the overrides, but would save a lot of time :)

Thanks for making this plugin!!!

**Comment by Ashung** [comment]
It's Sketch symbol update bug, because of the objectID of override layer in symbol master is changed or layer is deleted.

Imported Symbols Link Manage only change the library id of imported symbol.
