### ISSUE TITLE
Sketch 49 incompatibility

### ISSUE THREAD

**Issue by kemie** [Ashung/Automate-Sketch#54]
Several features are broken in sketch 49. Confirmed ones are Library-->imported symbols manage and library-->fix library incompatibility. Both of them just fail silently. I suspect there are problems with launching popups/dialogs

**Comment by kemie** [comment]
curious why this was closed. were you not able to reproduce it?

**Comment by Ashung** [comment]
Fixed it in V49.0.20180301.

**Comment by Ashung** [comment]
If current document have not any imported symbols, the dialog "Imported Symbols Link Manage" will not launch, you can see a message popup at bottom side of canvas.

**Comment by preciselykem** [comment]
yep, that one I see. But library id conflict just fails to launch without any message
