### ISSUE TITLE
Hey man, thanks a lot for the effort here! I've a request if possible.

### ISSUE THREAD

**Issue by 88fsantos** [Ashung/Automate-Sketch#56]
My team is working on a library file and that library is shared on Plant. The rest of the team create their own .sketch files and import symbols from that library. The problem is that sometimes, we loose the link between that symbols and the library. I guess that when there is an update on the library, it may change the ID or we may have some ID problem of some sort. Can you add a way to:
1- check current document ID
2- change current document ID
3- check imported library ID (and change it too)

Thanks a lot!

**Comment by Ashung** [comment]
Imported symbol have a library ID, and it is same as the document ID of the library file.

You can open the library file from Libraries panel in Preferences dialog, then open Run Script dialog from menu "Plugins - Run Script...", and run this code.

Show the document ID.

```
log(context.document.documentData().objectID());
```

Change document ID.

```
context.document.documentData().setObjectID("7667E82D-D65B-4EB1-8901-9807B2037CB6")
log(context.document.documentData().objectID())
```

Generate a new document ID.

```
context.document.documentData().generateObjectID();
log(context.document.documentData().objectID());
```

This will show all imported libraries and the library ID.

```
var assetLibraryController = NSApp.delegate().librariesController();
var documentData = document.documentData();
var foreignSymbols = documentData.foreignSymbols();
for (var i = 0; i < foreignSymbols.count(); i ++) {
    var foreignSymbol = foreignSymbols.objectAtIndex(i);
    var assetLibrary = assetLibraryController.libraryForShareableObject(foreignSymbol.symbolMaster());
    log(assetLibrary.name());
    log(assetLibrary.libraryID());
}
```

**Comment by 88fsantos** [comment]
Thanks a lot Man! This helps a lot!

I would only like to know why Sketch changes ID :S
