### ISSUE TITLE
Request:Batch insert symbols instances from master symbol page to any art board

### ISSUE THREAD

**Issue by Freurso** [Ashung/Automate-Sketch#57]
If this is possible ,PLZ let me know.Thanks Dude.

**Comment by Ashung** [comment]
Yes, why doing this?

**Comment by Freurso** [comment]
For instance. I've placed a bunch of icons in the master symbol page
without specific description.And i want to make an icon booklet with
specific description in another page of the same sketch file for my
colleagues to grab.I have to insert all this symbolized icons one by one In
old school way……so i am wondering it would helps a lot if i can insert
selected symbols to certain art board at one time. How does it sound? :P

**Comment by Ashung** [comment]
You can run script to doing this job.

Step 1. Select symbol masters.

Step 2. Run menu "Plugins" - "Run Script..." then replace with this code. You may need to change the code `pageIndex`, `columns` and `gap`, pageIndex 0 is the first page in page list from top to bottom.

```
var pageIndex = 0;
var columns = 10;
var gap = 20;

var document = context.document;
var page = document.pages().objectAtIndex(pageIndex);
var origin = page.originForNewArtboardWithSize(CGSizeMake(1000, 1000));
var x = origin.x;
var y = origin.y;
var rowHeight = 0;

var predicate = NSPredicate.predicateWithFormat("className == %@", "MSSymbolMaster");
var selectedSymbolMaster = context.selection.filteredArrayUsingPredicate(predicate);

for(var i = 0; i < selectedSymbolMaster.count(); i++) {
    if (i % columns == 0) {
        x = origin.x
        if (i != 0) {
            y += rowHeight + gap;
        }
    }
    var instance = documentData.localSymbols().objectAtIndex(i).newSymbolInstance();
    page.addLayer(instance);
    instance.frame().setX(x);
    instance.frame().setY(y);
    x += instance.frame().width() + gap;
    rowHeight = instance.frame().height() > rowHeight ? instance.frame().height() : rowHeight;
}
```

**Comment by Freurso** [comment]
something went wrong with an

ReferenceError: Can't find variable: documentData

Hope you fix this.Thx dude.

**Comment by Ashung** [comment]
Sorry. try again, i have changed the code.

**Comment by Freurso** [comment]
It worked.
But if the target page is totally blank, nothing would appear.
