### ISSUE TITLE
Feature Request: Arrange Top-left to Bottom-right

### ISSUE THREAD

**Issue by aentan** [Ashung/Automate-Sketch#58]
Right now I'm doing it by first ordering X then Y. Would be great to make it just one step.

**Comment by Ashung** [comment]
I have add "Arrange" - "Tile Objects" to version 49.3.20180410.

![image](https://user-images.githubusercontent.com/932544/38541007-5e0152d4-3cd0-11e8-8c8c-2970754bedf9.png)

![image](https://user-images.githubusercontent.com/932544/38541072-87743136-3cd0-11e8-8161-868c2514d626.png)
