### ISSUE TITLE
Feature Request : move all export applied symbols from current page to a particular page

### ISSUE THREAD

**Issue by Raghav789** [Ashung/Automate-Sketch#59]
thank you for this powerful plugin 
sketch Symbol page with all symbol is pretty good but it would be great if It can move the exportable symbol to separate page for example called 'assets' or any page user chooses.

**Comment by Ashung** [comment]
You can use "Automate" - "Symbol" - "Move Symbol Masters to Another Page", this will move selected symbol masters to a particular page or create a new page.

**Comment by Raghav789** [comment]
hmm but I still need to go and find all the symbols with slice applied, previously I could just turn on slice filter and select all the all the layers but, now sketch removed layer filtering option :(

**Comment by Raghav789** [comment]
Is there any way I can tile 24pt width symbols both vertically and horizontally with the same 24pt width?

**Comment by Ashung** [comment]
Select layers / symbol masters with same width / height / size?  You can use this plugin [sketch-select](https://github.com/canisminor1990/sketch-select). then use "Tile objects".

**Comment by Ashung** [comment]
For select symbols with slice, you can run this script.

Step 1. select the symbol page

Step 2. run menu "Plugins" - "Run Script...",  replace with this code. 

```
var document = context.document;
var page = document.currentPage();

page.changeSelectionBySelectingLayers(nil);

for (var i = 0; i < page.symbols().count(); i++) {
    var symbolMaster = page.symbols()[i];
    var childrenClasses = symbolMaster.children().mutableCopy().slice().map(function(child) {
        return child.class()
    });
    if (childrenClasses.indexOf(MSSliceLayer) != -1) {
        log(symbolMaster)
        symbolMaster.select_byExtendingSelection(true, true);
    }
}

```

**Comment by Raghav789** [comment]
I'm sorry but, nothing happened

**Comment by Ashung** [comment]
I use Sketch 49.3, It will select symbol master with slice layer inside.

**Comment by Raghav789** [comment]
That must be it. I'm in 49.2 thank you :)
