### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by edenvidal** [Ashung/Automate-Sketch#6]
1. Rearrange artboards (I think there is a plugin for this but it's not that good)
2. Killer feature - Regroup artborad - For rearranging layers by their position, if they share the same x-y-axis they are grouped (for example).

**Comment by Ashung** [comment]
@edenvidal 
1, you can use "Arrange" - "Align Objects" or "Make Grid..."
2, I don't understand what you mean, could you show me some picture.
