### ISSUE TITLE
Create / Sync Include Layer

### ISSUE THREAD

**Issue by swizenfeld** [Ashung/Automate-Sketch#60]
What does this do?

**Comment by ozgurgunes** [comment]
It creates/syncs instances of normal artboards (like symbols). I'm occasionally using it below modals, overlays etc. When I make changes in design of a page and sync includes, all instances dimmed by modal windows get updated. 

 @Ashung It's broken in 50 Beta. This is a bug report actually :)

**Comment by Ashung** [comment]
In new version V50.0.20180510, this is replaced by Create / Sync Link Layer, the link layer is a link symbol.

**Comment by swizenfeld** [comment]
Are there any videos or tutorials showing how it works?
