### ISSUE TITLE
Rename all instances of a symbol at once

### ISSUE THREAD

**Issue by nelsonalvesnqda** [Ashung/Automate-Sketch#61]
Hi there, 

before anything i must say Thank you for this awesome plugin.

One of my favourite features has Rename all instances of a symbol but it seems it isn't possible to do it anymore. 

Now i have to select an instance and only after that it is possible to rename it with is master symbol name. A few weeks ago i was able to select a symbol and rename all instances used across all artboards and pages. 

Is there any away to keep doing it?

**Comment by Ashung** [comment]
In v49.3.20180425. Rename all instances of a symbol, just select some symbol master, and run "Rename Instances".

If your select some symbol instances, it will rename the instances you selected. 

Deselected layers and run "Rename Instances", it will rename all instances in document.
