### ISSUE TITLE
remove hidden layers issue

### ISSUE THREAD

**Issue by illustree** [Ashung/Automate-Sketch#64]
when you have any layer selected the feature doesn't work ... only when nothing is selected it works: is it actually meant to be so? Should it probably work always?

**Comment by Ashung** [comment]
If you select a group or artboard, it will remove hidden layers in the group or artboard. when nothing is selected it will remove all hidden layer in current page.

**Comment by illustree** [comment]
yes, that makes sense of course! ... but if you have any layer selected it will just do nothing, that is the issue I guess ... should probably detect whether the selected layer is inside a group and then delete the stuff inside the group or artboard? thanks in any case for your respond
