### ISSUE TITLE
lots of things to do, can i use [tab] button?

### ISSUE THREAD

**Issue by everysundays** [Ashung/Automate-Sketch#69]
<img width="681" alt="screen shot 2018-05-15 at 1756 hrs" src="https://user-images.githubusercontent.com/6457060/40056274-0bbd1b78-5875-11e8-8249-3c6b66054a98.png">
is there a way I can [tab] [tab] [tab] around the frame to select & correct lots of links like this, this will help me a lot as I am now fighting a very long list of re-linking to a long lost library.

this is "import symbols link manage" feature which could help me out greatly.

if you can. Thank you!

**Comment by Ashung** [comment]
I'm no sure can use tab in popup menu, I can add a filter for only show library or symbol master is miss , or you can disable some library first.
