### ISSUE TITLE
Feature request - ability to copy symbols from one file to another

### ISSUE THREAD

**Issue by ibm-dziner** [Ashung/Automate-Sketch#71]
I love your plugin -- it was super helpful to be able to copy symbols to another page. Is there any way you could make this work for copying symbols across files?

**Comment by Ashung** [comment]
Just cmd-c and cmd-v

**Comment by ibm-dziner** [comment]
@Ashung 

That doesn't work, because I want the new symbols to take the place of existing symbols. Sorry, I wasn't clear in my original description.

I'm not using libraries, so I have a master file that has symbols, and when I update those symbols, I want my consumers to be able to use the new copies. So, basically, I want to replace older copies of the symbols with newer ones.

Here's the scenario:

1. User A has an existing Sketch file -- version 1.0. User A is using a symbol called "special_button".
2. I update special_button in the Master, and push the Master to User A.
3. User A wants to update the version of "special_button" in his copy of Sketch with my new version. User A tries copy/paste, but the new "special_button" symbol is not actually the one used in his Sketch file -- all his assets still refer to the original one. If he deletes the old special_button symbol, his instances are all detached.

Is there a way you can automate it this? You made it work within the existing Sketch file -- so I can move symbols from one page to another. Is there a way to replace symbols in a different file?

**Comment by Ashung** [comment]
Use "Symbol" - "Sync Symbol Master from Sketch File base Symbol ID" for update existing symbols.

You can convert local symbols to library symbols. use "Symbol" - "Change Symbols to Library Symbol Base Symbol ID" and "Symbol" - "Replace Symbol with Library Symbol".

Some plugins convert local symbols to library symbols base symbol name.
- [Library Symbol Replacer](https://github.com/zeroheight/library-symbol-replacer)
- [Symbol Swapper](https://github.com/sonburn/symbol-swapper)
- [Move to library](https://github.com/ahmedmigo/Move-to-library-sketchplugin)

**Comment by ibm-dziner** [comment]
Wow -- great info. Thank you so much!!!
