### ISSUE TITLE
Styles are not saved after import

### ISSUE THREAD

**Issue by CraigReville** [Ashung/Automate-Sketch#72]
Having an issue importing and saving layer and text styles from existing file.

1. Open file
2. Select to Import from existing file
3. It imports nicely and can check it in "Organize styles"
4. Save and close
5. Re-open, all the styles are gone

I've contacted Sketch regarding this issue, they refuse to accept it's their issue and asked me to contact you for support as it's a third-party app.

[GIF of issue](https://www.dropbox.com/s/5633w38m3gva5xr/issue_styles_25_05_2018.gif?dl=0)

**Comment by Ashung** [comment]
Fixed.
