### ISSUE TITLE
Remover layers not on artboards

### ISSUE THREAD

**Issue by mattbingco** [Ashung/Automate-Sketch#76]
I don't see an option to remove a layer(s) that is not on an artboard. That would be amazing!

**Comment by Ashung** [comment]
You means remove layers not in artboard area or artboard group?

![image](https://user-images.githubusercontent.com/932544/40818951-6414f77c-658c-11e8-816b-db962848956f.png)

**Comment by mattbingco** [comment]
Yes exactly. I have many items off of the art boards that I’d like to get
rid of (they are not visible)

Thanks for the quick response!
