### ISSUE TITLE
Popup panel

### ISSUE THREAD

**Issue by licheff** [Ashung/Automate-Sketch#77]
The plugin is awesome, I use it all the time. I think it would be great if there's a panel or some kind of a toolbox in order to speed up the process of finding a specific feature. There's an example attached. The plugin is [Charts](https://github.com/pavelkuligin/chart) :
<img width="160" alt="screen shot 2018-06-12 at 13 10 16" src="https://user-images.githubusercontent.com/29426217/41284529-3d184796-6e42-11e8-808a-0eeb3e2124da.png">

**Comment by Ashung** [comment]
Too much icons, you can use the Customize Menu of Sketch Runner.
