### ISSUE TITLE
Feature Request: Please add new function – Fast Slice

### ISSUE THREAD

**Issue by Mikola35** [Ashung/Automate-Sketch#79]
Often, I need to create this slice for android assets.
![image](https://user-images.githubusercontent.com/4017693/41422126-f171446c-7000-11e8-93c6-fae477137d1d.png)

Usually I use AutoSlice with 0 to create slice and 
different plugin "Webalize It" to rename layer.

Can u merge this operations to one function — Fast Slice?

**Comment by Mikola35** [comment]
Also, maybe u can separate Auto Slice to 2 different items:

**Comment by Ashung** [comment]
Update V50.2.20180621, I add this feature.

**Comment by Mikola35** [comment]
Yeah! That's cool!

**Comment by Mikola35** [comment]
But, numbers is need too.

![image](https://user-images.githubusercontent.com/4017693/41725635-fd37bd80-7578-11e8-888d-6c21c644cf27.png)
Red – incorrect
Green – correct

**Comment by Ashung** [comment]
Because of Android asset name can't start number, so I remove it. I'll fix it soon.

**Comment by Mikola35** [comment]
Thanks!
