### ISSUE TITLE
Feature Request: Pixel Fitting switch

### ISSUE THREAD

**Issue by Shavcat** [Ashung/Automate-Sketch#82]
You usually turn off Pixel Fitting in Preferences when drawing precise graphics in Sketch. I turn this option ON and OFF a lot of time during a day. Please consider an idea of adding this into Automate so users can bind a shortcut.
![image](https://user-images.githubusercontent.com/10747109/41711810-0352cdbe-755a-11e8-8fee-654751144caa.png)

**Comment by Ashung** [comment]
Run "Plugins" - "Run Script...", replace this code, then press save button. It will add a new plugin, so you can bind a shortcut.

```javascript
var userDefaults = NSUserDefaults.standardUserDefaults();
var pixelFitting = userDefaults.boolForKey("tryToFitToPixelBounds");
if (pixelFitting) {
    userDefaults.setBool_forKey(false, "tryToFitToPixelBounds");
}
else {
    userDefaults.removeObjectForKey("tryToFitToPixelBounds");
}
userDefaults.synchronize();
```

**Comment by Shavcat** [comment]
Thanks Ashang! Couldn't figure out to solve it this way, shame on me
