### ISSUE TITLE
Feature Request: "Select All Child Layers" include shape layer (group)

### ISSUE THREAD

**Issue by yanghaoleng** [Ashung/Automate-Sketch#85]
"Select All Child Layers" is very practical future , hope it can include shape layer (group).
Thank you !

**Comment by yanghaoleng** [comment]
哦，如果将形状图层也算作组，当形状图层和普通图层混合在一起的时候会有问题！
所以能否实现当单独选中一个有子图层的形状图层时，能够直接选中所有所有子图层的功能呢。

Oh, if the shape layer is also counted as a group, there will be problems when the shape layer is mixed with the normal layer！
So can you achieve the ability to directly select all the sublayers when you individually select a shape layer with sublayers?

**Comment by Ashung** [comment]
已修改。
