### ISSUE TITLE
Orders Groups by >

### ISSUE THREAD

**Issue by StudioMastro** [Ashung/Automate-Sketch#87]
Hi,
it'd be awesome if also groups could be arranged > ordered by > position x, position y, name or size.

I've tried but the option _Arrange Layers > Orders by >_ at the moment it's just for layers and not for **groups/folders**.

In case it's already possible, how?
Thanks! Your plugin, it's awesome!

**Comment by Ashung** [comment]
"Arrange" - "Order Layers By..." and "Reverse Layer Order" are for layer list order, and support all layer types.
