### ISSUE TITLE
Select layers by text style

### ISSUE THREAD

**Issue by Marrrrc** [Ashung/Automate-Sketch#88]
Hey, 

I think it would be awesome to be able to select layers matching the text style. It could really help maintaining a clean layer list, as well as improve the flow design<>dev for long-term projects.

This outdated plugin might serve as a starting point?
https://github.com/getflourish/Sketch-Select-Similar-Text-Layers-Plugin 

Anyway, I wanted to thank you for keeping your helpful plugin updated!

**Comment by Ashung** [comment]
It already have this feature, it will support library styles for Sketch 51 soon.

**Automate** - **Style** - **Select Layers by Text Style** & **Select Layers by Layer Style**

**Comment by Marrrrc** [comment]
Ah it's there indeed, my bad!
It's great that you are already catching up with the v51 library styles. 
You have my admiration and 6-bucks-worth of gratitude.
