### ISSUE TITLE
Feature request : Ignore path prefix in layer name while exporting.

### ISSUE THREAD

**Issue by Raghav789** [Ashung/Automate-Sketch#93]
In most of my project, I use layer path prefixes for my assets for easier access and switching
for Ex: song_player/control/ic_play
but, while export I want the sketch to ignore the folder structure in the layer and stick to the structure in the export 
in the above example ic_play in res/drawable-mdpi folder which I defined in an export preset. is it possible via some sort of script?  or an option in automates Sketch menu.

**Comment by Ashung** [comment]
You can use "Automate" - "Slice" - "Fast Slice" / "Fast Slice Setting". See this issue #79.

**Comment by Raghav789** [comment]
Thank you, but this would mean I need to create a separate slice just for export I'm the kind used to export directly from symbol or artboard. I was thinking of some sort of global toggle but, I could get used to this too.
