### ISSUE TITLE
Feature Request: Rename Text Layer to its Text Style

### ISSUE THREAD

**Issue by richardsison** [Ashung/Automate-Sketch#94]
What I'm trying to do is **Rename all Selected Text Layers** to its **corresponding Text Style**.

There's a plugin that does this for Symbols ([Symbol Instance Renamer](https://github.com/sonburn/symbol-instance-renamer)) but I'm trying to accomplish the same thing for Text Styles on my template artboard.

I rely on the plugin [Sketch Styles Generator Plugin](https://github.com/lucaorio/sketch-styles-generator) when making new variations and having a feature to make sure **All Text Layers** are named to their **corresponding Text Style** would be a super helpful whenever I'm doing this.

**Comment by Ashung** [comment]
Update V51.2.20180814, you can run "Style" - "Select Layer by Text/Layer Style", then run "Rename Layer to Style Name" (New).
