### ISSUE TITLE
Feature Request: Imported Symbols Link Manage - Bulk/Batch

### ISSUE THREAD

**Issue by richardsison** [Ashung/Automate-Sketch#95]
This feature really helped me out. While exporting my Sketch project from Abstract (which was a Sketch file and a Sketch library), the Sketch file lost its "link" to the Library that it was exported with. It was still trying to link back to the branch within Abstract.

So basically I needed to relink the "imported symbols" to a new library.

I was able to achieve this with the function: **Automate > Library > Imported Symbols Link Manage**, but it took a long time because of the number of Symbols.

Thanks!

**Comment by Ashung** [comment]
Add "Library" - "Replace Library".

![image](https://user-images.githubusercontent.com/932544/44092088-01d5bad2-a002-11e8-9e9b-0f8080ee8eb9.png)
