### ISSUE TITLE
Feature Request - Resize Shortcuts From Right / Bottom / Center

### ISSUE THREAD

**Issue by blaskotron** [Ashung/Automate-Sketch#97]
Right now the shortcuts for CMD + UP / DOWN / LEFT / RIGHT increase and decrease the selected objects' width and height by 1px with the addition of the SHIFT Key multiplying that by 10. 

However these originate from the top and left position. So only the right and bottom edges are moved with shortcut keys. 

On the width and height input field you can add a "c" for center origin, "r" for right origin, and "b" for bottom origin. 

I'd  like to request menu options to adjust width / height by these origins so they can be mapped to shortcuts. 

Increase Width by 1 from Right Origin
Increase Width by 10 from Right Origin
Increase Width by 1 from Center Origin
Increase Width by 10 from Center Origin
Increase Height by 1 from Bottom Origin
Increase Height by 10 from Bottom Origin
Increase Height by 1 from Center Origin
Increase Height by 10 from Center Origin

Decrease Width by 1 from Right Origin
Decrease Width by 10 from Right Origin
Decrease Width by 1 from Center Origin
Decrease Width by 10 from Center Origin
Decrease Height by 1 from Bottom Origin
Decrease Height by 10 from Bottom Origin
Decrease Height by 1 from Center Origin
Decrease Height by 10 from Center Origin

Thank you.

**Comment by Ashung** [comment]
I'm coding this features. 

Layer will increase or decrease with a small or large value, this value can be changed in "Preferences" - "Nudging", by default is 1 and 10. And the smallest layer width or height is 1 pixel.

Any suggest?

**Comment by blaskotron** [comment]
I think tying the values to that makes sense.
