### ISSUE TITLE
Feature Request: Select group's content on click (option for shortcut)

### ISSUE THREAD

**Issue by highvoltaged** [Ashung/Automate-Sketch#98]
As the title says, it would be great to be able to map that function to keyboard.
Thanks

**Comment by Ashung** [comment]
"Automate" - "Layer" - "Select All Child Layers"

**Comment by highvoltaged** [comment]
Sorry it might not have been a clear description.

There is a toggle switch on the inspector called "select group's content on click" if you select a group. 

I meant a script to toggle that.

**Comment by Ashung** [comment]
Oh, I know.

**Comment by Ashung** [comment]
Add "Layer" - "Toggle Select Group's Content on Click".
